from lib import theory

theory(4730,
   "Hence, Society may be defined as an enduring union of a number of persons morally bound under authority to cooperate for a common good.",
   "Outline the essential characteristics of a Society, and state the definition of Society which follows from them.",
   20,
   "The syllabus sets out five essential characteristics of a Society. First, there can be no existing Society without members, and only rational and free beings can form a Society, since it is a union based on agreement about goals. Secondly, the members must be united in a stable or enduring way; a passing association is not a Society. Thirdly, the members must cooperate or work together for the attainment of some end, and this end will be some common good that all the members will share in and that no member could accomplish singly. Fourthly, Society is held together by bonds, and these are moral bonds of means and ends: either the members bind themselves by contract, pledge or agreement, or the bonds are imposed upon them by some law, natural or positive. It is this moral bond that distinguishes a Society from a crowd, that makes the individuals committed members, and that obliges them to their commitment. Fifthly, to guide the cooperative effort to the common good, Society must be equipped with that moral power called authority, authority being the right to determine the means and to direct the members in their use. From these characteristics the syllabus draws its definition: Society may be defined as an enduring union of a number of persons morally bound under authority to cooperate for a common good. The syllabus adds a caution about the nature of a Society: it is not a physical thing. The only thing physical about a Society is the members and their action; the union itself is moral rather than material.",
   ["Members: only rational and free beings can form a Society",
    "The union is based on agreement about goals",
    "The members must be united in a stable or enduring way",
    "The members must cooperate for the attainment of some end",
    "That end is a common good all share in and none could accomplish singly",
    "Society is held together by moral bonds of means and ends, by contract, pledge or agreement, or imposed by law",
    "The moral bond distinguishes a Society from a crowd",
    "Authority is the moral power that guides the cooperative effort; it is the right to determine the means and direct the members",
    "Definition: an enduring union of a number of persons morally bound under authority to cooperate for a common good",
    "Society is not a physical thing; only the members and their action are physical"],
   [("Members and their nature",
     "States that a Society must have members, and that only rational and free beings can form one, since it is a union based on agreement about goals.",
     4, ["members", "rational", "free", "agreement", "goals"],
     [["rational", "reasonable", "reasoning"], ["free", "freedom", "free beings"], ["agreement", "consent", "accord"]], True),
    ("Stable and enduring union",
     "States that the members must be united in a stable or enduring way.",
     3, ["stable", "enduring", "united", "lasting"],
     [["stable", "settled", "permanent"], ["enduring", "lasting", "continuing"]], True),
    ("Cooperation for a common good",
     "Explains that members must cooperate for some end, which is a common good shared by all and unattainable by any member singly.",
     5, ["cooperate", "common good", "end", "together", "singly"],
     [["cooperate", "work together", "collaborate"], ["common good", "shared good", "good of all"]], True),
    ("Moral bonds",
     "Explains that Society is held together by moral bonds of means and ends, whether self-imposed by contract, pledge or agreement or imposed by natural or positive law, and that this bond distinguishes a Society from a crowd.",
     4, ["moral bond", "contract", "pledge", "agreement", "law", "crowd"],
     [["moral bond", "moral bonds", "bond"], ["contract", "covenant", "pledge", "agreement"], ["crowd", "mob", "mere gathering"]], True),
    ("Authority and the resulting definition",
     "States that Society must be equipped with the moral power called authority, defined as the right to determine the means and direct the members in their use, and gives the definition of Society that follows.",
     4, ["authority", "moral power", "right to determine the means", "definition", "enduring union"],
     [["authority", "moral power"], ["enduring union", "lasting union"], ["common good", "good of all"]], True)],
   "Tests recall of the five characteristics and the ability to show how the syllabus's definition of Society is built from them.",
   "medium", ["society", "definition", "characteristics"])

theory(4759,
   "The Church is in the Society though it is not of it. It is to address the issues that bother on the current political world, the current economic problems, high infant mortality rate, and the abuse of fundamental human rights.",
   "Discuss the key functions of the Church, with particular reference to its responsibility in and to the society in which it lives.",
   25,
   "The syllabus begins by insisting that the Church is not an institution but a people: the Bible calls it Laos theou, the people of God, a people whose institutions should help them to participate in God's action in the world, that is, in the liberation of man to freedom and responsibility. Its business is the business of Christ, which he himself spelt out in Luke 4:18, 19: to proclaim release to the captives and recovering of sight to the blind, to set at liberty those who are oppressed, and to proclaim the acceptable year of the Lord. The Church must be, as Harvey Cox puts it, like a confirmed gambler. The Church is in the Society though it is not of it. It is therefore to address the issues that bear on the current political world, current economic problems, high infant mortality rate and the abuse of fundamental human rights. Other areas named are hunger, intra and intertribal conflicts, inadequate housing and poverty; the contamination of water bodies, pollution of the atmosphere and the fast depletion of the natural forest; and human rights abuses and corruption in both government and society, where the Church is to be the voice of the voiceless. Christians are themselves part of the secular society: we live in it, depend on it, and it is in a real sense part of us. No one can function as a Christian, any more than as a human being, independently of the society which has moulded him. The Gospel says that God so loved the world, not only good and religiously minded people, so where men and women are, there the Church must be. There is a great deal of wickedness in the world, but secular does not in itself mean wicked; God does not stop his work when humans stop watching it. All who honestly work for the welfare of human society, whether or not they call themselves believers, may be said to be serving God, for he that is not against us is for us. Finally the Church is to remind Society of two things: that people already have a real experience of God through the secular gifts they take for granted, and that they are in the gravest danger of destroying themselves and their world together if they ignore or defy the law of God and God's transforming grace through the gift of Jesus Christ.",
   ["The Church is not an institution but a people, Laos theou",
    "Its institutions should help it share in God's action: the liberation of man to freedom and responsibility",
    "The business of Christ, spelt out in Luke 4:18, 19, is the business of the Church",
    "The Church is in the Society though not of it",
    "It must address political, economic, health, human rights, conflict, housing, poverty and environmental issues",
    "It is to be the voice of the voiceless against human rights abuses and corruption",
    "Christians are part of the secular society and cannot live in a vacuum",
    "Secular does not in itself mean wicked; God works beyond the Church",
    "The Church must remind Society of its real experience of God through secular gifts and of the danger of self-destruction"],
   [("The Church as a people",
     "States that the Church is not an institution but a people, Laos theou, the people of God, whose institutions serve participation in God's action in the world.",
     5, ["not an institution", "people", "Laos theou", "people of God", "liberation"],
     [["Laos theou", "laos theou", "people of God"], ["liberation", "freedom", "set free"]], True),
    ("The business of Christ",
     "Cites Luke 4:18, 19 and its three items: release to the captives and recovery of sight, liberty for the oppressed, and the acceptable year of the Lord.",
     5, ["Luke 4:18", "captives", "blind", "oppressed", "acceptable year"],
     [["captives", "prisoners"], ["oppressed", "downtrodden"], ["acceptable year", "year of the Lord"]], True),
    ("In the Society but not of it",
     "States the principle that the Church is in the Society though not of it, and lists the issues it must address.",
     6, ["in the society", "not of it", "political", "economic", "human rights", "poverty", "corruption", "pollution"],
     [["human rights", "fundamental human rights"], ["corruption", "graft"], ["pollution", "contamination", "environment"], ["voice of the voiceless", "voiceless"]], True),
    ("Christians as part of secular society",
     "Explains that Christians live in and depend on the secular society, cannot live in a vacuum, and that secular does not in itself mean wicked.",
     5, ["secular", "vacuum", "wicked", "dependent", "moulded"],
     [["secular", "secular society"], ["wicked", "evil"], ["vacuum", "isolation"]], False),
    ("The two reminders to Society",
     "States the two things the Church is to remind Society of: real experience of God through secular gifts, and the danger of self-destruction if the law of God is ignored or defied.",
     4, ["remind", "experience of God", "secular gifts", "destroying", "law of God"],
     [["destroying", "destruction", "destroy"], ["law of God", "God's law"], ["grace", "transforming grace"]], True)],
   "Tests whether the candidate can set out the syllabus's account of the Church's nature, its mandate in Luke 4:18-19, and its engagement with the concrete problems of society.",
   "medium", ["church", "society", "functions"],
   scripture=["Luke 4:18,19", "Luke 9:49-50"])

theory(4793,
   "Plato and Aristotle fought with the notion of freedom and justice, while Thomas Aquinas and other medieval theologians, discussed them in their writings.",
   "Give an account of the significant historical developments in the modern understanding of human rights, from the Magna Carta to the International Bill of Human Rights.",
   25,
   "The syllabus observes that human beings have thought about their duties and rights from the time they decided to live in societies: Plato and Aristotle wrestled with freedom and justice, and Thomas Aquinas and other medieval theologians discussed them in their writings. The modern developments begin in Britain with the Magna Carta, which King John was induced to sign in 1215, and among whose provisions were guarantees of freedom for the Church and of fair trial by one's peers. A second British milestone was the Bill of Rights of 1688-1689, which made the Crown subject to Parliament. The American Declaration of Independence of 1776, drafted by Thomas Jefferson, affirmed as self-evident that all men are created equal and that they are endowed by their Creator with certain inalienable rights, especially the right to life, liberty and the pursuit of happiness. Similar language was used in France's Declaration of the Rights of Man and of Citizens, promulgated by its National Assembly in 1789, which speaks of man's natural and inalienable rights. In 1941 President Roosevelt gave his famous State of the Union address, looking forward to a world founded upon essential freedoms: the freedom of every person to worship God in his own way, freedom from want and freedom from fear, adding to each the words everywhere in the world. The United Nations Organization was established in 1945, its charter reaffirming faith in fundamental human rights and in the dignity and worth of the human person, and Article 55 committing it to promote universal respect for human rights without distinction as to race, sex, language or religion. The United Nations then established the Human Rights Commission under the chairmanship of Eleanor, the widow of President Roosevelt, which prepared the Universal Declaration of Human Rights; its first part covers political and civil rights and its second economic, social and cultural rights, and it was adopted by the UN General Assembly in Paris on 10th December 1948, though not all nations ratified it. In 1966 the two International Covenants were published, in 1973 the Helsinki Conference on Security and Co-operation in Europe was held, whose Final Act of 1975 included a section on the respect of human rights and fundamental freedoms, and in 1976 the two International Covenants came into effect, so that the long dreamed-of International Bill of Human Rights became a reality.",
   ["Plato, Aristotle and Aquinas discussed freedom and justice before the modern period",
    "Magna Carta 1215, signed by King John: freedom for the Church, fair trial by one's peers",
    "British Bill of Rights 1688-1689 made the Crown subject to Parliament",
    "American Declaration of Independence 1776, drafted by Thomas Jefferson",
    "France's Declaration of the Rights of Man and of Citizens, promulgated 1789",
    "Roosevelt's 1941 State of the Union address on the essential freedoms",
    "The United Nations established 1945; charter preamble and Article 55",
    "Universal Declaration prepared under Eleanor Roosevelt, adopted in Paris on 10 December 1948",
    "1966 Covenants published; Helsinki 1973 and Final Act 1975; 1976 Covenants came into effect"],
   [("Early and British landmarks",
     "Names Plato, Aristotle and Aquinas, and gives the Magna Carta of 1215 with its provisions and the Bill of Rights of 1688-1689.",
     5, ["Magna Carta", "1215", "King John", "fair trial", "Bill of Rights", "1688", "Parliament"],
     [["Magna Carta", "Great Charter"], ["fair trial", "trial by one's peers", "trial by peers"], ["Parliament", "the Crown subject to Parliament"]], True),
    ("American and French declarations",
     "Gives the American Declaration of Independence of 1776 drafted by Thomas Jefferson, and France's Declaration of the Rights of Man and of Citizens of 1789.",
     5, ["1776", "Jefferson", "inalienable", "created equal", "1789", "National Assembly", "Rights of Man"],
     [["inalienable", "unalienable"], ["Jefferson", "Thomas Jefferson"], ["Rights of Man", "Declaration of the Rights of Man"]], True),
    ("Roosevelt and the founding of the United Nations",
     "Gives Roosevelt's 1941 State of the Union address with the essential freedoms, and the establishment of the United Nations in 1945 with its charter and Article 55.",
     5, ["1941", "Roosevelt", "State of the union", "freedom from want", "freedom from fear", "1945", "United Nations", "Article 55"],
     [["freedom from want", "want"], ["freedom from fear", "fear"], ["United Nations", "UN", "United Nations Organization"]], True),
    ("The Universal Declaration of Human Rights",
     "Gives the Human Rights Commission under Eleanor Roosevelt, the content of the Declaration and its adoption in Paris on 10 December 1948.",
     5, ["Universal Declaration", "Eleanor", "Commission", "Paris", "1948", "dignity", "civil", "cultural"],
     [["Eleanor", "Eleanor Roosevelt", "Roosevelt's widow"], ["Universal Declaration", "UDHR", "Declaration of Human Rights"]], True),
    ("Covenants and the International Bill of Human Rights",
     "Gives the publication of the two International Covenants in 1966, the Helsinki Conference of 1973 and its Final Act of 1975, and the coming into effect of the Covenants in 1976.",
     5, ["1966", "Covenants", "Helsinki", "1975", "Final Act", "1976", "International Bill"],
     [["Covenants", "International Covenants"], ["Helsinki", "Helsinki Conference"], ["International Bill", "International Bill of Human Rights"]], True)],
   "A dates-and-documents question of the kind the paper favours; the candidate must be able to place each landmark in order and attach the right name and provision to it.",
   "hard", ["human-rights", "dates", "history"])

theory(4818,
   "According to John Stott, the Biblical basis of human rights hinges on three words - \n\"dignity\", \"equality\" and \"responsibility\".",
   "Explain, following John Stott, the biblical basis of human rights under the three words \"dignity\", \"equality\" and \"responsibility\".",
   25,
   "John Stott begins from the questions how human beings have any rights at all, whence they acquired them, and what Christians have distinctively to contribute. His answer is that the origin of human rights is creation: man has never acquired them, nor has any government or other authority conferred them; we received them with our life from our Maker, and they are inherent in our creation. Fundamental to human rights, therefore, is the question of what it means to be human. The biblical basis hinges on three words. Human dignity is based on Genesis 1:27-28, where three issues stand out: our relationship to God, since God created man in his own image, so that we are God-like beings whose rational, moral and spiritual qualities separate us from the animals and relate us to God; our relationship to one another, since male and female he created them, from which it follows that sexuality is God's creation, marriage his institution and human companionship his purpose, so that whoever abuses these abuses God; and our relationship to the earth and its creatures, since God gave us dominion with instructions to subdue and cultivate the earth, from which are derived the right to work and to rest, to share in the earth's resources, to food, clothing and shelter, and to life and health. Christians may also speak of a surpassing dignity derived from the Creator redeeming and recreating us through the incarnation and atonement of his Son. Human equality follows: the tragedy, Stott says, is that human rights have not always meant equal rights, because the good gifts of the Creator are spoiled by human selfishness, so that the rights God gave to all equally degenerate into my rights on which I insist. The God we worship shows no partiality, and Moses told Israel that the Lord is the God who shows no partiality and accepts no bribes, so Israelite judges were to do justice to the small and the great alike (Deuteronomy 10:17-18). All human rights violations contradict the equality we enjoy by creation, and he who oppresses the poor shows contempt for their Maker (Proverbs 14:31). Human responsibility is the last word derived from our createdness: whenever rights are emphasised to the exclusion of responsibility we miss the biblical pattern, for the Bible calls us to defend other people's rights but, when it addresses us, emphasises our responsibilities. Our responsibility is to secure the other person's rights, forgoing our own in order to do so. Jesus Christ is the supreme model of this renunciation (Philippians 2:6-7), and Paul, who had rights as an apostle, renounced them for the sake of the Gospel (1 Corinthians 9).",
   ["The origin of human rights is creation; they were neither acquired nor conferred",
    "Dignity rests on Genesis 1:27-28 and three relationships",
    "Relationship to God: made in his image, with rational, moral and spiritual qualities",
    "Relationship to one another: male and female; sexuality, marriage and companionship are God's",
    "Relationship to the earth: dominion grounds the material and economic rights",
    "A surpassing dignity from redemption through the incarnation and atonement",
    "Equality: God shows no partiality; violations contradict the equality of creation",
    "Responsibility: the Bible emphasises our duties, not our rights",
    "Christ (Philippians 2:6-7) and Paul (1 Corinthians 9) as models of renouncing rights"],
   [("Creation as the origin of rights",
     "States Stott's answer that the origin of human rights is creation, that they were not acquired or conferred, and that the question of rights is the question of what it means to be human.",
     5, ["origin", "creation", "acquired", "conferred", "Maker", "inherent"],
     [["creation", "createdness", "created"], ["conferred", "granted", "given by government"], ["Maker", "Creator"]], True),
    ("Human dignity and the three relationships",
     "Expounds dignity from Genesis 1:27-28 under the relationships to God, to one another and to the earth and its creatures.",
     8, ["dignity", "image", "male and female", "subdue", "dominion", "companionship", "marriage"],
     [["image", "image of God", "God's image"], ["dominion", "rule", "subdue"], ["companionship", "fellowship"]], True),
    ("Redemption and surpassing dignity",
     "Notes the additional dignity derived from the Creator redeeming or recreating us through the incarnation and atonement of his Son.",
     3, ["redeeming", "recreating", "incarnation", "atonement"],
     [["redeeming", "redemption", "redeemed"], ["recreating", "re-creation"], ["atonement", "sacrifice"]], False),
    ("Human equality",
     "Explains that rights have not always meant equal rights, that God shows no partiality, and cites Deuteronomy 10:17-18 and Proverbs 14:31.",
     5, ["equality", "partiality", "selfishness", "Deuteronomy", "Proverbs", "oppresses the poor"],
     [["partiality", "favouritism", "favoritism"], ["selfishness", "selfish"], ["oppresses the poor", "oppression of the poor"]], True),
    ("Human responsibility",
     "Explains that the Bible emphasises responsibilities rather than rights, that we are to secure others' rights and forgo our own, and cites Christ and Paul as models.",
     4, ["responsibility", "duties", "forgo", "renounce", "Philippians", "1 Cor. 9"],
     [["responsibility", "responsibilities", "duty", "duties"], ["forgo", "renounce", "give up", "surrender"]], True)],
   "Tests the candidate's grasp of Stott's threefold framework and of the scriptures attached to each of its parts.",
   "hard", ["human-rights", "stott", "bible"],
   scripture=["Genesis 1:27-28", "Deuteronomy 10:17-18", "Proverbs 14:31", "Philippians 2:6-7", "1 Corinthians 9"])
