from lib import theory

theory(5223,
   "The early church condemned the homosexual life-style as contrary to the spirit of the \nGospel. Such practices were denounced mainly on the grounds that \"they are in themselves unnatural\".",
   "Give an account of what the church fathers, the medieval church and the Reformers are reported in the syllabus as saying about homosexual practice.",
   25,
   "The syllabus reports that the early church condemned the homosexual life-style as contrary to the spirit of the Gospel, and that such practices were denounced mainly on the grounds that they are in themselves unnatural. Tertullian wrote that all other frenzies of the lusts which exceed the laws of nature are impious towards both human bodies and sexes, and that they are banished not only from the threshold but also from all shelter of the Church, for they are not sins so much as monstrosities. John Chrysostom denounced such practices as unnatural, and in his commentary on Romans 1:26-27 observed that the delights of sodomy are an unpardonable insult to nature; he held such immoralities to be doubly destructive, first in that they jeopardise the race by deflecting the sexual organs from their primary procreative purpose, and secondly in that they sow disharmony and strife between man and woman, who are no longer impelled by their physical desires to live together peaceably. With reference to Genesis 19, St Augustine wrote that those shameful acts against nature, such as were committed in Sodom, ought everywhere and always to be detested and punished, and that if all nations were to do such things they would equally be held guilty of the same crime by the law of God, which has not so made men that they should use another in this way. The medieval church, the syllabus reports, was pastorally sensitive to the problems of those involved in such practices, but remained uncompromisingly opposed to the practices themselves; since such acts could not lead to procreation, they moved beyond the limits for sexual behaviour, and Thomas Aquinas considered them sins against nature, the most serious genus of sins of lust, no less grievous than bestiality. The major Reformers maintained the same resistance as the early Christians: Luther considered the presence and toleration of homosexual activity among the clergy as one of the worst symptoms of decay in the church, and a product of human failure to know and honour the true God. The syllabus places this material alongside the argument from nature and creation, in which theologians from Thomas Aquinas to Karl Barth relate their understanding of nature to the doctrine of creation, Barth pointing to the way male and female complement each other as people created in the image and likeness of God, and Aquinas stressing the procreative end of heterosexual intercourse.",
   ["The early church condemned the practice as contrary to the spirit of the Gospel, mainly as unnatural",
    "Tertullian: frenzies of the lusts exceeding the laws of nature; banished from all shelter of the Church",
    "John Chrysostom on Romans 1:26-27: an unpardonable insult to nature",
    "Chrysostom's two grounds: jeopardising the race, and sowing disharmony between man and woman",
    "St Augustine on Genesis 19: shameful acts against nature to be detested and punished everywhere",
    "The medieval church: pastorally sensitive but uncompromisingly opposed",
    "Thomas Aquinas: sins against nature, the most serious genus of sins of lust, no less grievous than bestiality",
    "Luther: toleration among the clergy one of the worst symptoms of decay in the church",
    "Barth and Aquinas relate nature to the doctrine of creation"],
   [("The early church's general position",
     "States that the early church condemned the practice as contrary to the spirit of the Gospel and denounced it mainly on the ground that it is in itself unnatural.",
     4, ["early church", "contrary", "spirit of the Gospel", "unnatural"],
     [["unnatural", "against nature", "contrary to nature"], ["early church", "early Christians"]], True),
    ("Tertullian",
     "Reports Tertullian's words on the frenzies of the lusts which exceed the laws of nature, and on banishing them from all shelter of the Church.",
     5, ["Tertullian", "frenzies", "laws of nature", "banish", "monstrosities"],
     [["banish", "banished", "excluded"], ["monstrosities", "monstrosity"]], True),
    ("John Chrysostom",
     "Reports Chrysostom's comment on Romans 1:26-27 and his two grounds: jeopardising the race by deflecting the organs from their procreative purpose, and sowing disharmony between man and woman.",
     6, ["Chrysostom", "Romans 1:26", "insult to nature", "procreative", "disharmony", "strife"],
     [["procreative", "procreation", "reproductive"], ["disharmony", "strife", "discord"]], True),
    ("St Augustine and the medieval church",
     "Reports Augustine's words with reference to Genesis 19, and the medieval church's pastoral sensitivity combined with uncompromising opposition, including Aquinas's judgement.",
     6, ["Augustine", "Genesis 19", "Sodom", "detested", "punished", "medieval", "Aquinas", "bestiality"],
     [["detested", "detest", "abhorred"], ["medieval", "mediaeval", "Middle Ages"], ["bestiality", "beasts"]], True),
    ("The Reformers",
     "Reports that the major Reformers maintained the same resistance as the early Christians, and gives Luther's judgement on toleration among the clergy.",
     4, ["Reformers", "Luther", "clergy", "decay", "honour the true God"],
     [["Reformers", "Reformation", "Reformer"], ["decay", "corruption", "decline"]], True)],
   "A named-authorities question of the kind the paper favours: the candidate must attach the right statement to the right father or Reformer.",
   "hard", ["sexuality", "church-fathers", "reformers"],
   scripture=["Romans 1:26-27", "Genesis 19"])

theory(5296,
   "The practice of homosexuality in Ghana occurs in various forms.",
   "Describe, as the syllabus presents it, the forms in which homosexual practice occurs in Ghana, and outline the call to Christian love that the syllabus makes in response.",
   20,
   "The syllabus states that the practice occurs in Ghana in various forms. Public knowledge of the female form, lesbianism, limited it to the practice of supi in the boarding system of high schools: the system whereby some girls take other girls in the school as sexual partners and engage in sexual activities in tents, that is student beds covered by bed sheets. In most cases the senior girls take advantage of innocent fresh students, and there are stories of junior students bullied into such relationships by seniors. Some lesbian relationships involve female tutors and female students; the syllabus reports a case in a female church institution where a student became involved with a foreign woman on the staff, an affair which lasted a long time and left the Ghanaian lady emotionally devastated and eventually mentally unwell after the foreigner left the country. The male form, sodomy, was until recent times prevalent among prison inmates, and compared with supi among girls the incidence of sodomy in boys' schools has been far less. Thus until recently homosexuality in Ghana was associated with institutional life, in prisons and schools; today it has spread outside the institutions to hotels, guest houses, student hostels and private homes, and although the practice is outlawed, youth and adults of both sexes are involved in it for carnal pleasure and for money, with same sex prostitution and partnerships gaining root underground. A further factor in its growth is sex tourism: some tourists visit the country for sexual adventures, and young people have been lured into same sex prostitution by the attractive cash payments, one reported incident involving local boys, European tourists and photographs intercepted by customs officers at the parcel section of the Post Office. Homosexual marriages remain unknown in Ghana because of the law, though in the name of human rights the international gay movement would join hands with local counterparts to lobby for recognition; South Africa is perhaps the only country in Africa that now permits same sex marriages. The syllabus then insists on a distinction between homosexual inclination or inversion, for which people may not be responsible, and homosexual acts, for which they are. In its call to Christian love it defines homophobia as the negative attitude of personal hatred and fear towards homosexuals, a mixture of irrational fear, hostility and even revulsion, which overlooks the fact that many are probably not responsible for their condition though they are for their conduct. Richard Lovelace calls for a double repentance: that gay people should renounce their homosexual lifestyle, and that the straight ones should renounce homophobia. At the heart of the homosexual condition, the syllabus says, is a deep loneliness, a natural human hunger for mutual love, a search for identity and a longing for completeness, which must be met in the local church family. It adds that the fact that some people are homosexual does not mean that very close same-sex friendships are to be discouraged, and points to Ruth and Naomi, David and Jonathan, and Paul and Timothy as healthy friendships in the Bible, while cautioning that such relationships should not be allowed to degenerate.",
   ["Lesbianism and the practice of supi in the boarding system of high schools",
    "Relationships between female tutors and female students, with the case reported in a female church institution",
    "Sodomy, until recently prevalent among prison inmates and far less common in boys' schools",
    "Homosexuality was associated with institutional life but has spread to hotels, guest houses, hostels and private homes",
    "Motives of carnal pleasure and money; same sex prostitution gaining root underground",
    "Sex tourism and the reported incident of the photographs intercepted at the Post Office",
    "Homosexual marriages unknown in Ghana because of the law; South Africa perhaps the only African country permitting them",
    "The distinction between inclination or inversion and acts",
    "Homophobia defined, and Richard Lovelace's call for a double repentance",
    "Healthy same-sex friendships: Ruth and Naomi, David and Jonathan, Paul and Timothy"],
   [("Lesbianism and supi",
     "Describes supi in the boarding system of high schools, including the involvement of senior students and of tutors.",
     5, ["lesbianism", "supi", "boarding", "seniors", "tutors"],
     [["lesbianism", "lesbian", "female homosexuality"], ["supi", "the practice of supi"], ["boarding", "boarding schools", "boarding house"]], True),
    ("Sodomy and the institutional setting",
     "Describes sodomy as prevalent among prison inmates, less common in boys' schools, and the former association of the practice with institutional life.",
     4, ["sodomy", "prison", "inmates", "institutional", "schools"],
     [["sodomy", "male homosexuality"], ["prison", "prisons", "inmates"], ["institutional", "institutions"]], True),
    ("Spread beyond the institutions",
     "States that the practice has spread to hotels, guest houses, student hostels and private homes, for pleasure and money, with same sex prostitution gaining root underground.",
     4, ["hotels", "guest houses", "hostels", "private homes", "money", "prostitution"],
     [["hotels", "hotel"], ["prostitution", "prostitutes", "same sex prostitution"], ["money", "cash", "payment"]], True),
    ("Sex tourism and the law",
     "Describes sex tourism as a factor in the growth of the practice, and notes that homosexual marriages remain unknown in Ghana because of the law, South Africa being perhaps the only African country permitting them.",
     4, ["sex tourism", "tourists", "lured", "law", "South Africa", "marriages"],
     [["sex tourism", "tourism", "tourists"], ["lured", "enticed", "attracted"]], True),
    ("The call to Christian love",
     "Distinguishes inclination or inversion from acts, defines homophobia, gives Lovelace's call for a double repentance, and notes the healthy same-sex friendships of the Bible.",
     3, ["inclination", "inversion", "acts", "homophobia", "Lovelace", "double repentance", "Jonathan"],
     [["inclination", "inversion", "orientation", "condition"], ["homophobia", "irrational fear"], ["double repentance", "repentance"]], True)],
   "Tests whether the candidate can reproduce the syllabus's own description of the local situation together with the pastoral response it prescribes.",
   "medium", ["sexuality", "ghana", "christian-love"],
   scripture=["1 Samuel 18:1-4", "2 Samuel 1:26"])
