from lib import theory

theory(5067,
   "Van der Walt concludes his discussion of secularism by describing it as the most dangerous enemy of Christianity.",
   "Explain why B. J. Van der Walt describes secularism as the most dangerous enemy of Christianity.",
   25,
   "Van der Walt concludes his discussion by describing secularism as the most dangerous enemy of Christianity, and draws attention to the conclusion of the World Mission Conference held in Jerusalem in 1982, that no student of the deeper problems of life can fail to see that the greatest rival of Christianity in the world today is not Mohammedanism, or Buddhism, or Hinduism, or Confucianism, but a worldwide secular way of life and interpretation of the nature of things. He gives three reasons in support. First, secularism is not an open enemy attacking the Christian faith with physical weaponry; it works practically unnoticed, and in a subtle way it infiltrates and undermines faith. Secondly, it works gradually from the outside to the inside: from the outside it might seem as if the Christian faith is still in order while living communion with God has in reality ceased to exist, and the process is so gradual that mostly we do not notice it any more, so that when we ultimately realise that an institution or the whole of life has been secularised it is already too late. Thirdly, it is not a clearly discernible and definable phenomenon: it is a sort of chameleon ideology, the medium for the growth of a variety of ideologies which in turn further promote the process of secularisation. Van der Walt nevertheless believes that we should neither under-estimate nor over-estimate the power of secularism, because the Gospel of Jesus Christ has power to conquer it. He concludes that only a radical, total, integral Christian worldview will be able to break the formidable power of secularism, not only in theory but concretely: in family life, in education, in politics, in the world of commerce and labour and even in the church. The syllabus adds that the Bible's clear response to this way of life is found in the Book of Ecclesiastes, where Solomon on reflection of his life found that it is a chasing after the wind, and that Yusufu Turaki advises that religion provides ethical and social values which affect people in their private and public lives and makes for responsible living, so that Christians must exhibit their Christian life (Matthew 5:13-16) in our secularised and materialistic societies in order to have influence.",
   ["Secularism described as the most dangerous enemy of Christianity",
    "The World Mission Conference, Jerusalem 1982, on the greatest rival of Christianity",
    "First reason: it is not an open enemy; it works unnoticed and infiltrates subtly",
    "Second reason: it works gradually from the outside to the inside, and realisation comes too late",
    "Third reason: it is a chameleon ideology, not clearly discernible or definable",
    "Neither under-estimate nor over-estimate it; the Gospel has power to conquer it",
    "Only a radical, total, integral Christian worldview can break its power",
    "Ecclesiastes: a chasing after the wind; Turaki on religion and responsible living; Matthew 5:13-16"],
   [("The Jerusalem 1982 conclusion",
     "Reports the World Mission Conference of 1982 and its conclusion that the greatest rival of Christianity is not another religion but a worldwide secular way of life.",
     5, ["Jerusalem", "1982", "World Mission Conference", "greatest rival", "Mohammedanism", "Buddhism", "secular way of life"],
     [["greatest rival", "greatest enemy", "chief rival"], ["Mohammedanism", "Islam"], ["secular way of life", "secularism"]], True),
    ("Not an open enemy",
     "Explains that secularism does not attack with physical weaponry but works practically unnoticed, infiltrating and undermining faith subtly.",
     5, ["open enemy", "physical weaponry", "unnoticed", "subtle", "infiltrates", "undermines"],
     [["unnoticed", "unseen", "imperceptibly"], ["subtle", "subtly"], ["infiltrates", "infiltrate", "penetrates"]], True),
    ("Works gradually from outside to inside",
     "Explains that faith may appear to be in order outwardly while living communion with God has ceased, and that realisation comes too late.",
     5, ["gradually", "outside", "inside", "communion", "too late"],
     [["gradually", "gradual", "slowly"], ["communion", "fellowship", "living communion"], ["too late", "already too late"]], True),
    ("A chameleon ideology",
     "Explains that secularism is not clearly discernible or definable and is the medium for the growth of other ideologies.",
     5, ["chameleon", "discernible", "definable", "ideologies", "medium"],
     [["chameleon", "chameleon ideology"], ["ideologies", "ideology", "isms"]], True),
    ("The Christian response",
     "States that the Gospel has power to conquer secularism, that only a radical, total, integral Christian worldview can break it, and may cite Ecclesiastes, Turaki or Matthew 5:13-16.",
     5, ["Gospel", "worldview", "radical", "integral", "Ecclesiastes", "chasing after the wind", "Turaki"],
     [["worldview", "world view", "world-view"], ["chasing after the wind", "chasing the wind", "vanity"], ["Gospel", "gospel of Jesus Christ"]], True)],
   "Tests whether the candidate can reproduce Van der Walt's three reasons and the conference conclusion the syllabus attaches to them.",
   "hard", ["pluralism", "secularism", "van-der-walt"],
   scripture=["Matthew 5:13-16"])

theory(5104,
   "The Church's position is found in Standing Order (SO) 743 of the Constitution under the \ntitle, Divorce, Dissolution of Marriage and Remarriage S.0.743:",
   "State and explain the position of the Methodist Church Ghana on divorce, dissolution of marriage and remarriage as set out in Standing Order 743.",
   25,
   "The position of the Methodist Church Ghana is found in Standing Order 743 of the Constitution, under the title Divorce, Dissolution of Marriage and Remarriage, as quoted from the Constitution and Standing Orders of the Methodist Church Ghana, 2000 Revised Edition. Its first provision is that no Member of the Church shall dissolve his or her marriage without first consulting his or her Minister, who shall make every effort to reconcile the parties and shall, if need be, seek the assistance of the Leader's Meeting. Secondly, if one partner fails in fulfilling the obligations of marriage, it is the duty of the other, as a Christian, to be active in seeking reconciliation so long as any possibility of it remains. Thirdly, where all efforts to effect reconciliation fail, the Leader's Meeting shall be informed of this. Fourthly, when one party has already formed a union with a third person and is judged to be beyond hope of restoration to the lawful partner, the latter may be permitted to dissolve the marriage by the appropriate process under the ordinance or Customary Law, and shall then be free to re-marry in due course; but this permission to divorce and re-marry is subject to confirmation by the Bishop of the Diocese, who shall act in consultation with the Circuit Superintendent concerned and a small committee, including a lawyer, appointed by Synod. Finally, any Member who dissolves his or her marriage against the advice of the Minister and the Leader's Meeting, or who is the guilty party in divorce proceedings, or who contravenes S.O. 742 (3) (1), shall be subject to the discipline of the Leader's Meeting. The syllabus adds that the peace or freedom principle established by Paul as a basis for divorce in mixed-faith marriages, resting on 1 Corinthians 7:15, may be extended to other cases after all efforts have been made to save a marriage, and that this appears to be the spirit of S.O. 743.",
   ["The position is in Standing Order 743, from the 2000 Revised Edition of the Constitution and Standing Orders",
    "No member may dissolve a marriage without first consulting the Minister",
    "The Minister must make every effort to reconcile the parties, seeking the Leader's Meeting if needed",
    "The other partner has a Christian duty to seek reconciliation so long as any possibility remains",
    "Where all efforts fail, the Leader's Meeting must be informed",
    "Where one party has formed a union with a third person and is beyond hope of restoration, the other may be permitted to dissolve the marriage and re-marry",
    "Permission is subject to confirmation by the Bishop of the Diocese, in consultation with the Circuit Superintendent and a committee including a lawyer appointed by Synod",
    "A member who acts against advice, or is the guilty party, is subject to the discipline of the Leader's Meeting",
    "The peace or freedom principle of 1 Corinthians 7:15 appears to be the spirit of S.O. 743"],
   [("The source of the position",
     "Identifies Standing Order 743 of the Constitution, under the title Divorce, Dissolution of Marriage and Remarriage.",
     3, ["Standing Order", "743", "Constitution", "Dissolution"],
     [["Standing Order", "S.O.", "SO", "Standing Orders"], ["Constitution", "Constitution and Standing Orders"]], True),
    ("Consultation and reconciliation",
     "States the duty to consult the Minister before dissolving a marriage and the Minister's duty to make every effort at reconciliation, with the Leader's Meeting if needed.",
     6, ["consulting", "Minister", "reconcile", "reconciliation", "Leader's Meeting"],
     [["consulting", "consult", "consultation"], ["reconcile", "reconciliation", "reconciling"]], True),
    ("The duty of the other partner and the reporting of failure",
     "States the Christian duty to be active in seeking reconciliation while any possibility remains, and that the Leader's Meeting must be informed where all efforts fail.",
     5, ["obligations", "duty", "possibility", "informed", "Leader's Meeting"],
     [["obligations", "obligation", "duties"], ["informed", "inform", "notified"]], True),
    ("Permission to dissolve and re-marry",
     "States the circumstances in which dissolution and remarriage may be permitted, and that permission is subject to confirmation by the Bishop of the Diocese in consultation with the Circuit Superintendent and a committee including a lawyer appointed by Synod.",
     7, ["third person", "beyond hope", "restoration", "re-marry", "Bishop", "Circuit Superintendent", "Synod", "lawyer"],
     [["re-marry", "remarry", "remarriage"], ["Bishop", "Bishop of the Diocese"], ["Circuit Superintendent", "Superintendent"]], True),
    ("Discipline and the freedom principle",
     "States that a member who dissolves a marriage against advice or who is the guilty party is subject to the discipline of the Leader's Meeting, and may relate the order to the peace or freedom principle of 1 Corinthians 7:15.",
     4, ["discipline", "guilty party", "against the advice", "freedom", "peace", "1 Cor. 7:15"],
     [["discipline", "disciplined", "disciplinary"], ["guilty party", "guilty"], ["freedom", "peace", "freedom principle"]], True)],
   "Tests exact recall of the Church's own standing order, which the paper commonly asks candidates to reproduce.",
   "hard", ["divorce", "methodist-church-ghana", "standing-orders"],
   scripture=["1 Corinthians 7:15"])

theory(5122,
   "For most people, divorce brings pain and turmoil, and affects people in many ways \nincluding the following:",
   "Describe the effects of divorce, and explain how the church should assist those who are going through it.",
   20,
   "The syllabus says that for most people divorce brings pain and turmoil, and affects people in many ways. There are emotional effects, including anxiety, guilt, fear, sadness, depression, anger, bitterness and frustration. There are behavioural effects, including declining work productivity and difficulties in completing routine tasks. There are social effects, including changing relationships with family, friends, work colleagues and fellow church members. There are physical effects, including increased illness and declining health. There are spiritual effects, in which some people draw closer to Christ while others drift away. And there are harmful effects on the children, even when the divorcing couple tries to make the separation smooth for them, and even upon adult offspring. The effects of divorce on the couple have been compared to what happens when one attempts to separate two sheets of paper which have been glued together: however carefully and skilfully this is done, the two sheets never get separated without each sheet being torn and damaged at several points. That, the syllabus says, is why Christians and the church must give prayerful support to those going through divorce and to the already divorced, as well as to the children and others who may be caught up in the tension. While the church must seek all available means to help couples to be faithful to the end, the rules against divorce cannot be handled mechanically. They must be applied with concern, understanding and prayer support, and in ways that will lighten the hurt, disappointment and burden of persons finding themselves in this situation.",
   ["Emotional effects: anxiety, guilt, fear, sadness, depression, anger, bitterness, frustration",
    "Behavioural effects: declining work productivity, difficulty completing routine tasks",
    "Social effects: changing relationships with family, friends, colleagues and fellow church members",
    "Physical effects: increased illness and declining health",
    "Spiritual effects: some draw closer to Christ, others drift away",
    "Harmful effects on children, including adult offspring",
    "The image of two sheets of paper glued together and then separated",
    "The church must give prayerful support to the divorcing, the divorced and the children",
    "The rules against divorce cannot be handled mechanically"],
   [("Emotional and behavioural effects",
     "Names the emotional effects and the behavioural effects on work productivity and routine tasks.",
     5, ["emotional", "anxiety", "guilt", "depression", "bitterness", "behavioural", "productivity"],
     [["emotional", "emotions"], ["behavioural", "behavioral", "behaviour"], ["productivity", "work productivity"]], True),
    ("Social, physical and spiritual effects",
     "Names the changing relationships, the increased illness and declining health, and the divided spiritual outcome.",
     6, ["social", "relationships", "physical", "illness", "health", "spiritual", "drift away"],
     [["social", "relationships"], ["illness", "sickness", "ill health"], ["drift away", "fall away", "backslide"]], True),
    ("Effects on children",
     "States that the effects are harmful to children even where the couple tries to make the separation smooth, and reach even adult offspring.",
     3, ["children", "offspring", "smooth", "harmful"],
     [["children", "child"], ["offspring", "adult children"]], True),
    ("The image of the glued sheets",
     "Gives the comparison with separating two sheets of paper glued together, neither of which comes away untorn.",
     3, ["sheets of paper", "glued", "torn", "damaged"],
     [["glued", "gummed", "stuck"], ["torn", "tear", "damaged"]], False),
    ("The church's assistance",
     "States that the church must give prayerful support to the divorcing, the divorced and the children, and that the rules cannot be applied mechanically but with concern, understanding and prayer.",
     3, ["prayerful support", "mechanically", "concern", "understanding", "burden"],
     [["prayerful support", "prayer support", "prayer"], ["mechanically", "mechanical", "rigidly"]], True)],
   "Tests both the six named categories of effect and the pastoral response the syllabus prescribes.",
   "medium", ["divorce", "effects", "pastoral-care"])

theory(5147,
   "Financial Strain: One does not have to be rich to have a successful marriage but when there is lack of money to take care of the basic needs of the family, it puts a \nstrain on the relationship.",
   "Describe five challenges that a marriage may face, and suggest how each may be met.",
   25,
   "The syllabus lists a number of challenges which, if not well handled, can lead to divorce, noting that the list is not exhaustive and that every couple must identify their own. The first is financial strain. One does not have to be rich to have a successful marriage, but lack of money for the basic needs of the family puts a strain on the relationship, and some couples plunge into this just after the wedding through failure to do proper financial planning on a short and long term basis. It can only be overcome by combining proper planning, hard work and a lifestyle which suits one's pocket instead of following what others do, and by being faithful to God, trusting him to give us the ability to create wealth (Deuteronomy 8:18); 1 Timothy 5:8 warns that whoever does not provide for his own household has denied the faith. The second is childlessness, a big challenge in cultures where childbearing is regarded as the principal reason for marriage; the woman is often falsely accused of barrenness, and the results include depression, disappointment, anxiety, shock, anger and feelings of sexual inadequacy. Since the causes may include infertility, miscarriage or loss of a child shortly after birth, the couple should seek medical guidance and appropriate marriage counsellors, show solidarity with each other, remember their vows, and after seeking medical help trust God and leave everything to his sovereign will; the godly offspring God desires (Malachi 2:15) does not involve biological children alone. The third is sexual unfulfilment, which arises where one partner feels not sufficiently catered for sexually, whether through differing levels of desire, misinformation about sex, harmful cultural values, the impact of pornography, busy lifestyles, stress and boredom, illness, psychological blocks or sexual dysfunction; it lowers self-esteem and may lead to involvement with alternative sexual activities and eventually to separation or divorce, so couples need to seek solutions to the basic causes with competent professionals. The fourth is the failure to keep the romance alive, which the syllabus compares to failing to nourish a child after birth, leading automatically to Kwashiorkor; the key is to continue with those practices that attracted one to the other during the pre-marital relationship, to make time for each other, and to take up hobbies and pastimes they enjoy, God himself having inspired the most romantic book in the world, the Song of Solomon. A fifth is my children versus my spouse, where more attention is given to the children at the expense of the spouse and parents take sides with the children, as happened with Isaac and Rebecca over Jacob and Esau; the couple must remember that the union before the altar was between husband and wife, and that the children will in future be united to their own partners. Other challenges named include transparency in times of prosperity, my spouse versus my career, travel abroad and the long absence of one partner, illustrated by Elimelech's family and Naomi returning alone as Marah, the little foxes of Song of Songs 2:15, and demonic influences, against which the couple's greatest weapon is the sharing of their spiritual lives, studying God's word and praying together.",
   ["Financial strain: proper planning, hard work, a lifestyle suited to one's pocket; 1 Timothy 5:8, Deuteronomy 8:18",
    "Childlessness: medical guidance, counselling, solidarity, trust in God's sovereign will; Malachi 2:15",
    "Sexual unfulfilment: its causes, its consequences, and recourse to competent professionals",
    "Keeping the romance alive: the Kwashiorkor comparison and the remedy of time and shared pastimes",
    "My children versus my spouse: Isaac and Rebecca over Jacob and Esau",
    "Transparency in times of prosperity; my spouse versus my career",
    "Travel abroad and long absence: Elimelech, Naomi and Marah (Ruth 1)",
    "The little foxes (Song of Songs 2:15): temperament, in-laws, communication",
    "Demonic influences (Ephesians 6:10-18) and the couple's shared spiritual life"],
   [("Financial strain",
     "Explains the strain caused by lack of money, the failure of financial planning, and the remedy of proper planning, hard work and a suitable lifestyle, with scripture.",
     5, ["financial", "money", "planning", "hard work", "lifestyle", "1 Tim", "provide"],
     [["financial", "finance", "money"], ["planning", "plan", "budget"], ["lifestyle", "life style", "living within one's means"]], True),
    ("Childlessness",
     "Explains why childlessness is a heavy challenge in such cultures, its emotional results, and the remedies of medical guidance, counselling, solidarity and trust in God.",
     5, ["childlessness", "barren", "childbearing", "medical", "counsellors", "solidarity", "Malachi"],
     [["childlessness", "childless", "barrenness"], ["counsellors", "counselors", "counselling", "counseling"], ["solidarity", "support one another", "stand together"]], True),
    ("Sexual unfulfilment",
     "Explains what sexual unfulfilment is, names some of its causes and consequences, and prescribes recourse to competent professionals.",
     5, ["sexual unfulfilment", "libido", "desire", "self-esteem", "professionals", "pornography"],
     [["sexual unfulfilment", "sexual unfulfillment", "sexual dissatisfaction"], ["libido", "sexual desire", "desire"], ["professionals", "professional help", "counsellors"]], True),
    ("Keeping the romance alive",
     "Explains the neglect of romance after marriage, the Kwashiorkor comparison, and the remedies of time together and shared pastimes.",
     5, ["romance", "Kwashiorkor", "nourish", "time", "hobbies", "Song"],
     [["romance", "romantic"], ["nourish", "nourishment", "feed"], ["hobbies", "pastimes", "interests"]], True),
    ("A fifth challenge, well explained",
     "Gives any further challenge named in the syllabus - children versus spouse, prosperity, career, travel abroad, the little foxes, or demonic influences - with its remedy.",
     5, ["children", "career", "prosperity", "travel abroad", "little foxes", "demonic", "spiritual"],
     [["little foxes", "foxes"], ["demonic", "satanic", "spiritual forces of evil"], ["travel abroad", "long absence", "abroad"]], True)],
   "Tests breadth of recall across a long list, and whether the candidate can attach the syllabus's own remedy and scripture to each challenge named.",
   "medium", ["marriage", "challenges"],
   scripture=["1 Timothy 5:8", "Deuteronomy 8:18", "Malachi 2:15", "Ruth 1", "Song of Songs 2:15", "Ephesians 6:10-18"])
