from lib import theory

theory(4869,
   "For its many inherent weakness, Winston Churchill once remarked, \"Democracy is the worst form of government except for all the others\".",
   "Discuss the inherent weaknesses of democracy identified in the syllabus, and show how the Church can help to sustain democracy.",
   25,
   "Churchill remarked that democracy is the worst form of government except for all the others: it is not perfect, but it is better than any other form known to man. The syllabus identifies seven inherent weaknesses and attaches to each a suggestion for the Church. The Tyranny of Democracy is the tendency of politicians to look out for the interest of the majority while neglecting or abusing the rights of the minority, which is especially dangerous where the majority is of a particular racial, ethnic, religious or ideological orientation; the Church can help ensure that government is fair to all its constituents and that minority rights are protected. The Fallacy of Democracy is committed when one defends the tyranny of the majority by arguing that democracy is by definition the rule of the majority; this is a conceptual blunder, since majority rule does not imply minority suffering, and the Church can expose the error and press for non-discrimination, a role supported by Galatians 3:28. The Disease of Democracy is the frequent election of representatives who make wonderful promises, fail to keep them, and attend to their constituents only when re-election is near; the Church should educate members to study candidates carefully and should train and encourage altruistic mature Christians to stand for office. Red Tapeism is the tendency to complicate and unduly delay administrative and legal procedures, breeding frustration, bribery and even resort to arms; the Church should advise those in administration to minimise delays, and should organise experienced church leaders, superannuated clergy, lawyers and retired judges and magistrates into Christian Family Arbitration Centres to settle cases out of court and decongest the legal system. Democracy is also a Catalyst for Ethnic Conflicts, since previously oppressed groups seize the opportunity of the prevailing wind of change, and the right to self determination in particular, to separate from their former oppressors; churches in conflict-prone areas must be part of the early warning system, keep security agents informed, and preach and counsel against such destabilising moves. The Problem of Vagueness arises because the tenets of democracy - freedom, justice, equality, peace, unity - are inherently vague and ambiguous, so that it is difficult to determine when they have been achieved; the Church can sensitise people to this ambiguity and to how such terms are manipulated by political adventurers and opposition parties. Finally there is Vulnerability to Military Coups: Africa alone has witnessed about fifty coups, in all of which corruption is cited as a common major cause; through military chaplains, guest preachers to the barracks and the mass media the Church should show that corruption is part of human nature and cannot be removed by coups, and should commend the checks and balances of democracy and the removal of corrupt politicians through the ballot box without bloodshed. In addition, the churches should pray for the state and supplement government's efforts by establishing schools, vocational and technical institutes and agricultural research centres.",
   ["Churchill: democracy is the worst form of government except for all the others",
    "The Tyranny of Democracy: majority interest at the expense of minority rights",
    "The Fallacy of Democracy: defending majority tyranny by definition; Galatians 3:28",
    "The Disease of Democracy: broken promises and re-election-driven service",
    "Red Tapeism: undue delay, bribery, and Christian Family Arbitration Centres",
    "Catalyst for Ethnic Conflicts: democratisation and the right to self determination",
    "The Problem of Vagueness: freedom, justice, equality, peace and unity are ambiguous",
    "Vulnerability to Military Coups: about 50 coups in Africa, corruption the common cause",
    "The Church should also pray for the state and supplement government's efforts in education and agriculture"],
   [("Churchill and the framing of the problem",
     "Quotes or paraphrases Churchill's remark and states that democracy, though imperfect, is better than the alternatives.",
     3, ["Churchill", "worst form of government", "imperfect", "better"],
     [["Churchill", "Winston Churchill"], ["worst form", "worst form of government"]], False),
    ("Tyranny and Fallacy of Democracy",
     "Explains the tyranny of the majority and the fallacy that defends it, with the Church's role in protecting minority rights and exposing the conceptual error; may cite Galatians 3:28.",
     6, ["tyranny", "fallacy", "majority", "minority", "Galatians", "discrimination"],
     [["tyranny", "tyranny of the majority", "tyranny of democracy"], ["fallacy", "conceptual blunder", "conceptual error"], ["minority", "minorities"]], True),
    ("Disease of Democracy and Red Tapeism",
     "Explains the failure of elected representatives to keep promises, and the undue delay of administrative and legal procedures, with the Church's suggested remedies including Christian Family Arbitration Centres.",
     6, ["disease", "promises", "re-election", "Red Tapeism", "delay", "bribe", "Christian Family Arbitration Centres"],
     [["Red Tapeism", "red tape", "red-tapeism"], ["delay", "delays", "frustration"], ["bribe", "bribery", "corruption"], ["Christian Family Arbitration Centres", "arbitration centres"]], True),
    ("Ethnic conflicts and vagueness",
     "Explains the correlation between democratisation and ethnic conflict, the right to self determination, and the vagueness of democratic terminology, with the Church's roles of early warning and sensitisation.",
     5, ["ethnic", "self determination", "early warning", "vagueness", "ambiguous", "freedom", "justice"],
     [["ethnic", "ethnic conflict", "tribal"], ["self determination", "self-determination"], ["early warning", "early warning system"], ["vagueness", "vague", "ambiguity", "ambiguous"]], True),
    ("Military coups and corruption",
     "Explains the vulnerability of these democracies to coups, gives corruption as the common major cause cited in about fifty African coups, and states the Church's role through chaplains, preachers and the mass media.",
     5, ["coups", "corruption", "50", "fifty", "chaplains", "ballot box", "checks and balances"],
     [["coups", "coup", "military take-overs", "military takeovers"], ["corruption", "graft"], ["ballot box", "voting", "vote"]], True)],
   "Tests whether the candidate can name each named weakness of democracy and pair it with the Church's suggested response.",
   "hard", ["politics", "democracy", "church-and-state"],
   scripture=["Galatians 3:28"])

theory(4927,
   "He argues that the unwillingness of many Christians to participate in politics is partly rooted in a failure to distinguish between party politics and political \nparticipation.",
   "Explain why, according to Kantiok, African Christians should participate in politics.",
   20,
   "The syllabus takes this material from an article in the ABC Commentary. Kantiok argues that the unwillingness of many Christians to take part in politics is partly rooted in a failure to distinguish between party politics and political participation. Political participation, he says, includes exercising one's right to vote and be voted for, speaking out against any wrongdoing by those in power, and holding leaders accountable for their actions. He observes that while Christians tend to avoid political participation, Muslims understand its importance, and consequently control political power in many African states, even where they are a minority; unlike Christians they do not believe in the separation of church and state, because that encourages secularism. Kantiok adds that Jesus too did not separate religion and politics: in his mission statement in Luke 4:18-19 he declared that his ministry was to those suffering various forms of bondage and oppression, including economic oppression, that is poverty, physical oppression, that is disease and disabilities, political oppression, that is injustice and oppressive rule, and demonic oppression, that is various forms of occult practices. Other biblical examples of political participation include Joseph in Egypt, who saved many from hunger and starvation (Genesis 41), Amos, who warned the political leaders of his time against injustice, Daniel and his three friends, and Nehemiah. In the New Testament Paul refused to give up his rights as a citizen when the political authorities put him in prison and flogged him without giving him a proper trial (Acts 16:37-38; 22:25). Kantiok therefore advises that moral bankruptcy, corruption, poverty, disease and ignorance all clearly call for Christian participation in politics, and concludes that African Christians need to understand that the destinies of their nations rest on their political participation.",
   ["The failure to distinguish party politics from political participation",
    "Political participation: voting and being voted for, speaking out, holding leaders accountable",
    "Muslims understand its importance and control power in many African states",
    "Jesus did not separate religion and politics: Luke 4:18-19",
    "Four forms of oppression: economic, physical, political and demonic",
    "Biblical examples: Joseph, Amos, Daniel and his three friends, Nehemiah",
    "Paul refused to give up his rights as a citizen (Acts 16:37-38)",
    "Moral bankruptcy, corruption, poverty, disease and ignorance call for participation",
    "The destinies of African nations rest on Christian political participation"],
   [("The distinction Kantiok draws",
     "States that Christian unwillingness is rooted in failing to distinguish party politics from political participation, and defines political participation.",
     5, ["party politics", "political participation", "vote", "accountable", "speaking out"],
     [["party politics", "partisan politics"], ["accountable", "accountability", "hold leaders accountable"]], True),
    ("The comparison with Muslims",
     "Reports Kantiok's observation that Muslims understand the importance of political participation and control power in many African states, rejecting the separation of church and state as encouraging secularism.",
     4, ["Muslims", "minority", "separation", "secularism"],
     [["Muslims", "Muslim", "Islam"], ["separation", "separation of church and state"], ["secularism", "secular"]], False),
    ("Jesus and the mission statement",
     "Cites Luke 4:18-19 and the four forms of oppression Kantiok identifies: economic, physical, political and demonic.",
     5, ["Luke 4:18", "oppression", "economic", "physical", "political", "demonic"],
     [["economic", "poverty"], ["physical", "disease", "disabilities"], ["demonic", "occult"]], True),
    ("Biblical examples of participation",
     "Names Joseph in Egypt, Amos, Daniel and his three friends, Nehemiah, and Paul's insistence on his rights as a citizen.",
     4, ["Joseph", "Amos", "Daniel", "Nehemiah", "Paul", "citizen"],
     [["Joseph", "Joseph in Egypt"], ["citizen", "citizenship", "Roman citizen"]], True),
    ("Kantiok's conclusion",
     "States that moral bankruptcy, corruption, poverty, disease and ignorance call for Christian participation, and that the destinies of African nations rest upon it.",
     2, ["moral bankruptcy", "corruption", "poverty", "disease", "ignorance", "destinies"],
     [["destinies", "destiny", "future"], ["moral bankruptcy", "immorality"]], True)],
   "Tests the candidate's grasp of the argument of the ABC Commentary article as the syllabus reproduces it, including its biblical examples.",
   "medium", ["politics", "christians-and-politics", "kantiok"],
   scripture=["Luke 4:18-19", "Genesis 41", "Acts 16:37-38"])

theory(4972,
   "Six common causes of conflict may be identified:",
   "What are the six common sources of conflict identified in the syllabus? Explain each briefly.",
   25,
   "The syllabus identifies six common causes of conflict. The first is differences in perception: no two individuals perceive things in the same way, and this often leads to misunderstanding, confusion and conflict. The second is differences in priority or values. Values are deeply held beliefs, and conflicts often develop when people with different value systems try to work together; value conflicts arise over differences in religious, moral, ideological or philosophical outlooks, and where conflict concerns values people have difficulty in changing their stand. The third is differences in expectations or role pressures: conflicts often arise over different expectations when these are not fulfilled, as when one person says I wanted you to and the other replies I expected you to. The fourth is divergent goals. The syllabus illustrates this with Yaw Nkrumah and Kwadwo Nsiah, who work for the same organisation but in different departments: Yaw wants to help the company make more profit by improving the quality of their products while Kwadwo wants more profit by decreasing costs; this leads to competition among managers for available resources, and lack of team effort can develop into enormous conflict situations. The fifth is self-esteem or status threat: Yaw may have a good idea, but Kwadwo's self-esteem depends on his having all the good ideas, and since Kwadwo is the boss and bosses know best, status and authority become sources of anger and frustration. The sixth is personality clashes: troublesome individuals have hostile natures and are predisposed toward conflict, people with strong needs to bully use their jobs to express hostility, and individuals with low self-esteem often overcompensate by being belligerent or hostile toward other people.",
   ["Differences in perception: no two individuals perceive things the same way",
    "Differences in priority or values: values are deeply held beliefs, hard to change",
    "Value conflicts arise over religious, moral, ideological or philosophical outlooks",
    "Differences in expectations or role pressures: unfulfilled expectations",
    "Divergent goals: the example of Yaw Nkrumah and Kwadwo Nsiah, and competition for resources",
    "Self-esteem or status threat: status and authority become sources of anger and frustration",
    "Personality clashes: hostile natures, bullying, and overcompensation for low self-esteem"],
   [("Differences in perception",
     "States that no two individuals perceive things in the same way, leading to misunderstanding, confusion and conflict.",
     4, ["perception", "misunderstanding", "confusion"],
     [["perception", "perceive", "perceptions"], ["misunderstanding", "misunderstandings"]], True),
    ("Differences in priority or values",
     "Explains values as deeply held beliefs and names the religious, moral, ideological or philosophical outlooks over which value conflicts arise.",
     5, ["values", "deeply held", "religious", "moral", "ideological", "philosophical"],
     [["values", "value", "priorities"], ["deeply held", "deeply held beliefs", "convictions"]], True),
    ("Differences in expectations or role pressures",
     "Explains that conflicts arise over expectations that are not fulfilled, and may give the illustrative exchange.",
     4, ["expectations", "role pressures", "fulfilled", "I expected you to"],
     [["expectations", "expectation"], ["role pressures", "roles", "role pressure"]], True),
    ("Divergent goals",
     "Explains divergent goals, ideally with the Yaw Nkrumah and Kwadwo Nsiah illustration, and the competition for available resources.",
     4, ["divergent goals", "profit", "quality", "costs", "resources", "team effort"],
     [["divergent goals", "different goals", "divergent goal"], ["resources", "available resources"]], True),
    ("Self-esteem or status threat",
     "Explains how status and authority become sources of anger and frustration when a superior's self-esteem depends on having all the good ideas.",
     4, ["self-esteem", "status", "authority", "boss", "frustration"],
     [["self-esteem", "self esteem", "esteem"], ["status", "status threat"]], True),
    ("Personality clashes",
     "Explains hostile natures predisposed to conflict, bullying, and overcompensation by individuals with low self-esteem.",
     4, ["personality", "hostile", "bully", "belligerent", "overcompensate"],
     [["personality", "personality clash", "personality clashes"], ["hostile", "hostility"], ["bully", "bullying"]], True)],
   "A straight list-and-explain question of the kind the paper sets; the candidate must name all six and give the syllabus's gloss on each.",
   "medium", ["conflict", "sources"])

theory(4996,
   "He proposes the following five principles which must guide us in resolving conflicts:",
   "Outline the five principles which Tokunboh Adeyemo proposes for resolving conflicts, together with the biblical examples he cites.",
   25,
   "Tokunboh Adeyemo, in his article in the ABC Commentary, writes that when we manage a conflict we simply organise, regulate and take charge of it in order to make it serve a good cause. He says that in resolving any conflict there are three key questions to ask: what are we agreeing or disagreeing about, why are we agreeing or disagreeing, and how can we get past this and move forward. He then proposes five principles. The first is honest communication: silence and isolation deepen misunderstanding, which fuels conflict; in Genesis 13:1-18 Abraham did not gloss over the potential for quarrels between his herdsmen and those of Lot, but discussed it openly with Lot and developed an appropriate strategy to deal with it. The second is getting beneath surface issues and unseen motives: often the apparent cause of a conflict is not the real issue, the conflict being rooted in people's underlying motives and beliefs which they may not have clearly identified; in Genesis 26:19-31 the real problem between the people of Gerar and Isaac went beyond water. The third is negotiation: the best way to find peace is through a process of give and take in which neither party insists on being the winner, and the story of 1 Kings 12 shows the disastrous consequence of Rehoboam's unwillingness to negotiate. The fourth is external intervention: the parties may be so caught up in the conflict that they have difficulty talking to one another and reaching agreement, in which case the assistance of a neutral person such as a marriage counsellor, or of an organisation such as the United Nations, may be sought; in Acts 15:1-2 Paul and Barnabas and their opponents took their case to the apostles in Jerusalem. The fifth is divine intervention: there is a spiritual dimension to conflicts, so in resolving them we need to seek divine assistance, and the Council at Jerusalem resolved the crisis that would have permanently divided the church into Jews and Gentiles (Acts 15:23-29).",
   ["Adeyemo's definition of managing conflict: organise, regulate and take charge so that it serves a good cause",
    "Three key questions: what, why, and how do we move forward",
    "Honest communication - Abraham and Lot, Genesis 13:1-18",
    "Getting beneath surface issues and unseen motives - Isaac and the people of Gerar, Genesis 26:19-31",
    "Negotiation - Rehoboam's refusal, 1 Kings 12",
    "External intervention - Paul and Barnabas before the apostles, Acts 15:1-2",
    "Divine intervention - the Council at Jerusalem, Acts 15:23-29"],
   [("Managing conflict and the three key questions",
     "Gives Adeyemo's definition of managing a conflict and the three key questions to ask in resolving one.",
     5, ["organize", "regulate", "take charge", "good cause", "three key questions", "agreeing", "disagreeing"],
     [["organize", "organise"], ["good cause", "serve a good cause"], ["disagreeing", "disagreement"]], True),
    ("Honest communication",
     "States that silence and isolation deepen misunderstanding, and cites Abraham and Lot in Genesis 13:1-18.",
     5, ["honest communication", "silence", "isolation", "Abraham", "Lot", "Genesis 13"],
     [["honest communication", "open communication", "honesty"], ["silence", "isolation"]], True),
    ("Getting beneath surface issues",
     "Explains that the apparent cause is often not the real issue, and cites Isaac and the people of Gerar in Genesis 26:19-31.",
     5, ["surface", "motives", "unseen", "Isaac", "Gerar", "water", "Genesis 26"],
     [["motives", "motive", "underlying motives"], ["surface", "surface issues", "apparent cause"]], True),
    ("Negotiation",
     "Explains negotiation as give and take in which neither party insists on winning, and cites Rehoboam in 1 Kings 12.",
     5, ["negotiation", "give and take", "winner", "Rehoboam", "1 Kings 12"],
     [["negotiation", "negotiate", "negotiating"], ["give and take", "compromise"]], True),
    ("External and divine intervention",
     "Explains recourse to a neutral third party, citing Acts 15:1-2, and the need for divine assistance, citing the Council at Jerusalem in Acts 15:23-29.",
     5, ["external intervention", "neutral", "counselor", "United Nations", "divine", "Jerusalem", "Acts 15"],
     [["external intervention", "third party", "neutral person", "mediation"], ["divine", "divine intervention", "God's intervention"], ["Jerusalem", "Council at Jerusalem", "Council of Jerusalem"]], True)],
   "Tests recall of the five named principles together with the biblical case attached to each, which is where the paper's marks usually lie.",
   "medium", ["conflict", "management", "adeyemo"],
   scripture=["Genesis 13:1-18", "Genesis 26:19-31", "1 Kings 12", "Acts 15:1-2", "Acts 15:23-29"])
