# -*- coding: utf-8 -*-
# Flashcards - all five units

CARDS = [

# ============================ MARK ============================

dict(t=648, b=655, kind="person", tags=["mark", "authorship"],
     front="Who wrote the Gospel according to Mark, and what was his relationship to Paul and to Peter?",
     back="John Mark. He was not one of the Twelve, but he accompanied Paul on his missionary journey (Acts 13:13), and Peter called him his 'son' (1 Pet. 5:13). Papias and Irenaeus described him as Peter's interpreter.",
     exc="Author: John Mark. He was not one of the Twelve apostles but he accompanied Paul on his missionary journey (Acts 13: 13). The apostle Peter referred to Mark as his \"son\" (1 Pet. 5: 13).",
     scr=["Acts 13:13", "1 Peter 5:13"]),

dict(t=648, b=659, kind="fact", tags=["mark", "date"],
     front="When was the Gospel of Mark written, and in what setting?",
     back="Between A.D. 55 and 65, in the Roman Empire under Tiberius Caesar.",
     exc="Date Written: Between A. D. 55 and 65.",
     scr=[]),

dict(t=648, b=663, kind="scripture", tags=["mark", "key-verse"],
     front="What is the key verse of Mark's Gospel?",
     back="'For even the Son of Man did not come to be served, but to serve, and to give His life a ransom for many' (Mark 10:45).",
     exc="Key Verse: \"For even the Son of Man did not come to be served, but to serve, and to give His life a ransom for many\" (10: 45).",
     scr=["Mark 10:45"]),

dict(t=648, b=669, kind="fact", tags=["mark", "special-features"],
     front="What three special features of Mark's Gospel does the syllabus name?",
     back="It was the first Gospel written; the other Gospels quote all except 31 verses of Mark; and it records more miracles than any other Gospel.",
     exc="Special Features: The Book was the first Gospel written. The other Gospels quote all except 31 verses of Mark. The Book of Mark records more miracles than does any other Gospel.",
     scr=[]),

dict(t=648, b=667, kind="fact", tags=["mark", "places"],
     front="Which key places does the syllabus list for the Gospel of Mark?",
     back="Capernaum, Nazareth, Caesarea Philippi, Jericho, Bethany, the Mount of Olives, Jerusalem and Golgotha.",
     exc="Key Places: Capernaum, Nazareth, Caesarea, Philippi, Jericho, Bethany, Mount of Olives, Jerusalem, Golgotha.",
     scr=[]),

dict(t=672, b=674, kind="definition", tags=["mark", "titles-of-jesus"],
     front="What is the meaning of the name 'Jesus', and of the title 'Christ'?",
     back="'Jesus' is His divinely given personal name, whose Hebrew equivalent is 'Joshua', that is, 'Yaweh is Salvation'; 'Christ' is the Greek equivalent of the Hebrew title Masiah (Messiah, Anointed).",
     exc="Its Hebrew equivalent (of the Greek is) \"Joshua\" i.e. \"Yaweh\" is Salvation. \"Christ\" is the Greek equivalent of the Hebrew title Masiah (Messiah, Anointed).",
     scr=["Luke 1:31"]),

dict(t=700, b=715, kind="fact", tags=["mark", "capernaum"],
     front="Which town became the hub of Jesus' Galilean ministry, and whose hometown was it?",
     back="Capernaum, the hometown of the four disciples who first accompanied Him.",
     exc="The four disciples accompanied Jesus into nearby Capernaum. It was their hometown and it became the hub of Jesus' Galilean ministry",
     scr=["Luke 4:16-31"]),

dict(t=700, b=731, kind="fact", tags=["mark", "prayer"],
     front="On which three occasions does Mark portray Jesus at prayer?",
     back="Near the beginning of the account (1:35), near the middle (6:46) and near the end (14:32-42) - each in a setting of darkness and aloneness, when facing His messianic mission.",
     exc="Mark selectively portrayed Jesus at prayer on three crucial occasions, each in a setting of darkness and aloneness:",
     scr=[]),

dict(t=743, b=773, kind="event", tags=["mark", "fasting"],
     front="How did Jesus answer the criticism that His disciples did not fast?",
     back="His presence among His people was as much an occasion for rejoicing as a bridegroom among the wedding guests; but a time would come when the Bridegroom would be taken from them, and in that day - His crucifixion - the disciples would fast.",
     exc="Jesus' reply was that His presence among His people was as much an occasion for rejoicing as was that of a bridegroom among the guests at his wedding.",
     scr=[]),

dict(t=743, b=789, kind="fact", tags=["mark", "sabbath"],
     front="What two principles emerge from Jesus' reply about plucking grain on the Sabbath?",
     back="That the Sabbath was instituted by God for mankind's benefit and refreshment, not to burden people with regulations; and that, since it was ordained for human well-being rather than as an end in itself, humanity's Lord and Representative is authorised to be the official arbiter of how it should be observed.",
     exc="That the Sabbath was instituted (by God) for mankind's benefit and refreshment Not that people were to be made to keep burdensome regulations pertaining to it.",
     scr=["1 Samuel 21:1-6"]),

dict(t=795, b=813, kind="fact", tags=["mark", "the-twelve"],
     front="For what two reasons did Jesus choose the Twelve?",
     back="So that they could be with Him, and to be sent out by Him to preach and to have authority to drive out demons.",
     exc="To be sent out by Him to preach, and to have authority to drive out demons (vs. 14-15).",
     scr=[]),

dict(t=795, b=824, kind="definition", tags=["mark", "blasphemy", "holy-spirit"],
     front="What is the sin against the Holy Spirit, according to the syllabus?",
     back="An attitude of defiant hostility towards God that rejects His saving power expressed in the Spirit-empowered person and work of Jesus - a person's preference for darkness though exposed to light, which can harden into a condition in which repentance and forgiveness become impossible.",
     exc="This refers to an attitude of defiant hostility towards God that rejects His saving power towards man, expressed in the Spirit empowered person and work of Jesus.",
     scr=["John 3:19"]),

dict(t=829, b=863, kind="fact", tags=["mark", "miracles"],
     front="Which four acts of divine power are related in Mark 4:35 - 5:43?",
     back="The calming of a violent storm; the healing of a demoniac; the raising of the daughter of Jairus; and the healing of the woman with an issue of blood.",
     exc="From 4:35 to 5:43 are related four acts of divine power wrought by Jesus in a situation of human helplessness and despair:",
     scr=[]),

dict(t=869, b=893, kind="fact", tags=["mark", "faith", "healing"],
     front="To what did Jesus attribute the cure of the woman with the issue of blood, and what did the address 'Daughter' signify?",
     back="The cure was attributed to her faith rather than to the touch of His clothing; the address 'Daughter' suggested her new relationship with Him, and 'Go in peace and be healed' assured her that the healing was complete and permanent.",
     exc="The cure was also attributed to her faith rather than the touch of His clothing.",
     scr=[]),

dict(t=899, b=917, kind="fact", tags=["mark", "anointing", "healing"],
     front="Why did the Twelve anoint the sick with oil?",
     back="Both because of its medicinal properties and for its symbolic value, indicating that the disciples acted by Jesus' authority and power and not their own; it is also to be thought of as an accessory to miraculous healing and a stimulus to faith.",
     exc="The anointing with the oil was both because of its medicinal properties (cf. Lk. 10:34; James 5:14) and its symbolic value indicating that the disciples acted by Jesus' authority and power, not their own.",
     scr=["Luke 10:34", "James 5:14"]),

dict(t=899, b=915, kind="fact", tags=["mark", "mission-of-the-twelve"],
     front="How is the threefold ministry of the Twelve summarised in Mark 6:12-13?",
     back="Preaching repentance, driving out demons and healing the sick - showing that Jesus' power extended beyond His personal presence.",
     exc="The threefold ministry of the Twelve is summarized as preaching repentance, driving out demons and healing the sick.",
     scr=[]),

dict(t=952, b=964, kind="fact", tags=["mark", "hypocrisy", "isaiah"],
     front="Why did Jesus call the religious leaders 'hypocrites', quoting Isaiah 29:13?",
     back="Because they made an outward profession of worshipping God but gave Him no genuine worship from their hearts.",
     exc="They were \"hypocrites\" because they made an outward profession of worshipping God but gave Him no genuine worship from their hearts.",
     scr=["Isaiah 29:13"]),

dict(t=952, b=987, kind="event", tags=["mark", "miracles", "faith"],
     front="Why did Jesus use saliva, touch and an upward look in healing the deaf and dumb man?",
     back="He used sign language and symbolic acts suited to the man's needs, to awaken faith by encouraging him to expect healing; being deaf, the man could not hear a vocal prayer, so by looking up to heaven Jesus indicated that He was praying.",
     exc="He used saliva (v. 31), touching also the ears and tongue, apparently to awaken in the man faith by encouraging him to expect healing.",
     scr=[]),

dict(t=989, b=1017, kind="definition", tags=["mark", "leaven"],
     front="What was the leaven of the Pharisees, and what was the leaven of Herod?",
     back="From Luke 12:1 we learn that the leaven of the Pharisees was hypocrisy; the leaven of Herod was irreligion, and the leaven of bread was probably worldliness and sensuality. In context the yeast referred to a gradual increase of unbelief.",
     exc="We learn from Luke 12:1 that leaven of the Pharisees was hypocrisy; the leaven of bread",
     scr=["Luke 12:1"]),

dict(t=1021, b=1035, kind="fact", tags=["mark", "passion-predictions"],
     front="Where are the three predictions of the passion found in Mark?",
     back="Mark 8:31, 9:31 and 10:33; from Peter's confession onwards the narrative is dominated by the thought of the approaching passion.",
     exc="The narrative, from this point is dominated by the thought of the approaching passion, of which there are three definite predictions. (8:31; 9:31; 10:33)",
     scr=["Isaiah 53"]),

dict(t=1040, b=1042, kind="definition", tags=["mark", "discipleship"],
     front="What does it mean to deny oneself and take up one's cross, according to Mark 8:34?",
     back="To abandon the attitude of self-centredness, and to take up one's own (not His) cross - in other words, to be prepared to die.",
     exc="Any person who enlisted in His cause would need to deny himself (v. 34) that is, abandon the attitude of self- centeredness, and take up his own (not His) cross, in other words be prepared to die.",
     scr=[]),

dict(t=1040, b=1068, kind="fact", tags=["mark", "greatness", "service"],
     front="What did Jesus say the essence of greatness is, when the disciples argued about who was the greatest?",
     back="That it lay in performing acts of service for other people; He illustrated servant-leadership by taking a child in His arms, one who represented the lowliest disciple.",
     exc="Jesus told them that the essence of greatness lay in performing acts of service for other people (v. 35, also 10:43-44).",
     scr=["Luke 9:47"]),

dict(t=1081, b=1088, kind="fact", tags=["mark", "kingdom-of-god", "children"],
     front="What did Jesus mean by saying 'the kingdom of God belongs to such as these' when the children were brought to Him?",
     back="That the kingdom belongs to people who, though not literally children, are imbued with such childlike characteristics as trust and receptiveness; it is not gained by human achievement or merit but must be received as God's gift through simple trust.",
     exc="God's kingdom is not gained by human achievement or merit; it must be received as God's gift through simple trust by those who acknowledge their inability to gain it any other way.",
     scr=[]),

dict(t=1110, b=1119, kind="fact", tags=["mark", "temple", "gentiles"],
     front="What had the Court of the Gentiles become, and why was Jesus outraged?",
     back="The high priest Caiaphas had authorised a market there for ritually pure items, and the merchants and money changers turned it into a bazaar, making it impossible for any Gentile to use the area for prayer; Jesus was outraged by this disregard for the area set apart for Gentile use, since the temple was intended as a house of prayer for all nations.",
     exc="In it the High priest Caiaphas had authorized a market for the sale of ritually pure items necessary for temple sacrifice: wine, oil, salt, approved sacrificial animals and birds.",
     scr=["Exodus 30:13-16"]),

dict(t=1131, b=1136, kind="event", tags=["mark", "taxes", "caesar"],
     front="Why was the question about paying the poll tax to Caesar a trap, and how did Jesus answer it?",
     back="To insist on payment would alienate the people; to deny its legitimacy would allow Him to be reported to Rome as a rebel. Jesus replied that since the money bore the Emperor's image it was Caesar's property and the tax should be paid, adding that they should give back to God what is God's.",
     exc="Obviously the question was designed to place Jesus in a religious and political dilemma.",
     scr=[]),

dict(t=1202, b=1218, kind="fact", tags=["mark", "judas", "betrayal"],
     front="What suggestions does the syllabus offer for why Judas betrayed Jesus?",
     back="That Judas, the only non-Galilean of the Twelve, may have responded to the official orders to report Jesus' whereabouts; that he was disillusioned by Jesus' failure to establish a political kingdom; and that his love for money moved him. What is clear is that he came under satanic control.",
     exc="Judas, the only non-Galilean member of the Twelve, may have responded to the official",
     scr=["John 11:57", "Luke 22:3"]),

# ============================ ACTS ============================
dict(t=1382, b=1384, kind="person", tags=["acts", "luke", "authorship"],
     front="Who wrote the Book of Acts, and what does Paul call him?",
     back="Luke, a medical officer and companion of Paul, whom Paul calls 'Our dear friend Luke, the doctor' (Col. 4:14) and a colleague (Philemon 24); it can be inferred that he was Greek.",
     exc="Paul refers to him as \"Our dear friend Luke, the doctor\" (Col. 4:14) and as a colleague (Philemon 24).",
     scr=["Colossians 4:14", "Philemon 24", "2 Timothy 4:11"]),

dict(t=1382, b=1396, kind="fact", tags=["acts", "purpose", "theology"],
     front="What theological purpose does Acts serve?",
     back="It gives guidance to the church on how to live until Jesus comes again, and on how to transmit the gospel to people who had never seen Jesus in the flesh.",
     exc="In terms of its theology, Acts gives guidance to the church on how to live until Jesus comes again and on how to transmit the gospel to people who had never seen Jesus in the flesh.",
     scr=[]),

dict(t=1399, b=1421, kind="fact", tags=["acts", "apostleship", "matthias"],
     front="What two qualifications were required of the candidates for the twelfth apostleship?",
     back="They must be well-known members of the apostolic band, associated with them during the ministry of Jesus; and they must be witnesses to His resurrection.",
     exc="They must be well-known members of the apostolic band, associated with them during the ministry of Jesus.",
     scr=[]),

dict(t=1399, b=1414, kind="definition", tags=["acts", "ascension"],
     front="How does the syllabus define the Ascension?",
     back="The withdrawal of Jesus from our vision but not from the world.",
     exc="The Ascension is the withdrawal of Jesus from our vision but not from the world (Mt. 28:20).",
     scr=[]),

dict(t=1427, b=1431, kind="fact", tags=["acts", "pentecost", "tongues"],
     front="How does Pentecostal glossolalia differ from the spiritual gift of 1 Corinthians 14?",
     back="The Pentecostal tongue-speaking is apparently different; the 1 Corinthians account of tongue-speaking is to be used in private and public worship, and with caution and restraint.",
     exc="This Pentecostal glossolalia (tongue speaking) is apparently different from the spiritual gift in 1 Corinthians 14.",
     scr=["1 Corinthians 14"]),

dict(t=1427, b=1442, kind="scripture", tags=["acts", "church", "fellowship"],
     front="Which verse is called the church's birthday description, and what four things did the believers devote themselves to?",
     back="Acts 2:42 - they devoted themselves continually to the apostles' teaching, to fellowship, to the breaking of bread and to prayer.",
     exc="\"And they were continually devoting themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer\" (v. 42).",
     scr=["Acts 2:42"]),

dict(t=1475, b=1485, kind="fact", tags=["acts", "deliverance", "prison"],
     front="Which are the three miraculous jail releases in Acts?",
     back="The release of the apostles in Acts 5, of Peter in Acts 12:6-10, and of Paul and Silas in Acts 16:26-27.",
     exc="In Acts this is the first of three miraculous jail releases (cf. Peter, 12:6-10; Paul and Silas, 16:26-27).",
     scr=[]),

dict(t=1501, b=1510, kind="person", tags=["acts", "stephen", "philip", "the-seven"],
     front="Who were the two most prominent members of 'the seven' appointed to represent the Hellenists?",
     back="Stephen, who had a grasp of the universal character of the Gospel and became a key figure in early Christian history; and Philip, who carried the Gospel to Samaria and West Judea.",
     exc="One other prominent member of the \"seven\" was Philip who carried the Gospel to Samaria and West Judea.",
     scr=[]),

dict(t=1501, b=1515, kind="fact", tags=["acts", "stephen", "moses"],
     front="What did Stephen's face like the face of an angel signify?",
     back="It was exactly what happened to Moses' face when he came down from Mount Sinai with the Law, apparently showing that both Moses' ministry of the Law and Stephen's interpretation of it have God's approval.",
     exc="This is exactly what happened to Moses' face when he came down from Mount Sinai with the Law (Ex. 34:29).",
     scr=["Exodus 34:29"]),

dict(t=1566, b=1568, kind="fact", tags=["acts", "saul", "paul", "names"],
     front="What is the relation between the names Saul and Paul?",
     back="Saul is the Hebrew name and Paul the Greek name of the same person; his conversion marked a significant turning point in the missionary agenda of the church.",
     exc="Saul is the Hebrew name and Paul the Greek name of the same person.",
     scr=[]),

dict(t=1591, b=1595, kind="person", tags=["acts", "dorcas", "peter"],
     front="Who was Dorcas, and what did Peter do at Joppa?",
     back="A well-beloved Christian woman and disciple of Joppa, known for her help to the poor. When she died Peter came from Lydda, prayed and commanded her to get up; to avoid ceremonial defilement he apparently did not touch her until after God restored her to life.",
     exc="While Peter was at Lydda, a well-beloved Christian woman (a disciple) in Joppa, called Dorcas, died. She was known for her help to the poor.",
     scr=["Leviticus 21:1", "Numbers 5:2"]),

dict(t=1607, b=1628, kind="fact", tags=["acts", "antioch", "christians"],
     front="Where were the disciples first called Christians?",
     back="At Antioch, which became the springboard for mission to the Gentile world.",
     exc="Significantly, the disciples were first called Christians at Antioch.",
     scr=[]),

dict(t=1607, b=1623, kind="person", tags=["acts", "barnabas"],
     front="For what reasons was Barnabas a wise choice to be sent to Antioch?",
     back="He was a Levite who, like some of the Christian ambassadors, came from Cyprus; he was a generous person and therefore thoughtful of others; and he was gracious, as his nickname 'Son of encouragement' attests. Luke sums him up as 'a good man, and full of the Holy Spirit and of faith'.",
     exc="He was a gracious person, attested to by his nick name, \"Son of encouragement\" (4:36).",
     scr=[]),

dict(t=1607, b=1632, kind="event", tags=["acts", "agabus", "famine"],
     front="What did Agabus prophesy, and when did it occur?",
     back="A great famine. Josephus reports that a great famine occurred in about AD 46 - actually a series of severe famines that struck various sections of the Roman Empire during the reign of Emperor Claudius, AD 41-54.",
     exc="(Josephus reports that a great famine occurred in about AD 46. These were actually a series of severe famines that struck various sections of the Roman Empire during the reign of Emperor Claudius - AD 41-54.)",
     scr=[]),

dict(t=1663, b=1666, kind="fact", tags=["acts", "antioch", "missions"],
     front="What change of centre and of leadership took place from Acts 13 onwards?",
     back="Jerusalem was still the mother church, but Antioch became the missionary church and Saul's headquarters; Peter was no longer the central figure, for Saul had become the central figure. From Antioch he started his journeys, and to Antioch he returned to report.",
     exc="Jerusalem was still the mother church, but the missionary church was Antioch. Peter was no longer the central figure, Saul had become the central figure.",
     scr=[]),

dict(t=1742, b=1744, kind="fact", tags=["acts", "holy-spirit", "macedonian-call"],
     front="How is the ministry of the Holy Spirit seen in the call to Macedonia?",
     back="In both restraining and constraining the missionaries: Paul was making for Ephesus but God stopped him, he moved towards Bithynia and again God stopped him, and finally at Troas God gave positive direction by a vision to go to Macedonia.",
     exc="The ministry of the Holy Spirit here is seen in both restraining (vs. 6-7) and constraining the missionaries (v 9).",
     scr=[]),

dict(t=1742, b=1757, kind="scripture", tags=["acts", "philippi", "jailer", "salvation"],
     front="What answer did Paul and Silas give the Philippian jailer's question, 'What must I do to be saved?'",
     back="'Believe in the Lord Jesus and you will be saved' - showing that all that is needed for justification is faith in the Lord Jesus; the jailer did not need to perform any work, he only needed to believe.",
     exc="The answer they gave, \"Believe in the Lord Jesus and you will be saved,\" shows that all that is needed for justification is faith in the Lord Jesus.",
     scr=[]),

dict(t=1798, b=1822, kind="person", tags=["acts", "apollos", "alexandria"],
     front="Who was Apollos?",
     back="A native of Alexandria and an educated Jew well versed in the Scriptures, whose name is an abbreviated form of Apollonius. Aquila and Priscilla realised his message was incomplete and instructed him further; he became a leader in the Corinthian church and at Ephesus.",
     exc="He was a native of Alexandria, an educated Jew well versed in the scriptures.",
     scr=["1 Corinthians 3:6", "1 Corinthians 16:12", "Titus 3:13"]),

dict(t=1830, b=1865, kind="term", tags=["acts", "the-way"],
     front="By what name did Paul refer to Christianity, and where is the term found?",
     back="'The Way' - a term used only in Acts (19:9, 23; 22:4; 24:14, 22).",
     exc="Saul (Paul) referred to Christianity as \"the Way\", a term used only in Acts (19: 9, 23; 22:4; 24:14, 22).",
     scr=[]),

dict(t=1830, b=1844, kind="fact", tags=["acts", "holy-spirit", "tongues"],
     front="Does the reception of the Holy Spirit in Acts follow a set pattern?",
     back="No. In Acts 2:1-4 the Holy Spirit came after salvation; in Acts 10:44 He came to believers before baptism; in Acts 19:6 He was manifested at the time of or after baptism. These instances cannot be used as a doctrinal source on how to receive the Holy Spirit.",
     exc="the reception of the Holy Spirit in Acts does not follow any set patterns.",
     scr=["Acts 2:1-4", "Acts 10:44", "Acts 19:6"]),

dict(t=1869, b=1876, kind="fact", tags=["acts", "worship", "troas"],
     front="What does the meeting at Troas tell us about the worship of the early churches?",
     back="They were held on 'the first day of the week' - Sunday; there was breaking of bread, that is the Eucharist, and a sermon was preached. On this occasion the service was held in the evening and dragged on until there was a fatal accident.",
     exc="They were held on \"the first day of the week\" - Sunday. There was breaking of bread - the Eucharist, and a sermon was preached.",
     scr=[]),

dict(t=1885, b=1893, kind="person", tags=["acts", "philip", "prophecy", "women"],
     front="Who was Paul's host at Caesarea, and what is notable about his daughters?",
     back="Philip the evangelist, one of the seven who ministered to widows in Jerusalem. He had four unmarried daughters who had the gift of prophecy - showing that this spiritual gift was not limited to men.",
     exc="He had four unmarried daughters who had the gift of prophecy.",
     scr=[]),

dict(t=1945, b=1949, kind="fact", tags=["acts", "felix", "accusations"],
     front="What three accusations did Tertullus bring against Paul before Felix?",
     back="That Paul was a worldwide trouble maker, stirring up riots everywhere; that he was a leader of the Nazarene sect; and that he attempted to desecrate the temple.",
     exc="Paul was a worldwide trouble maker, stirring up riots everywhere.",
     scr=[]),

dict(t=1990, b=1998, kind="fact", tags=["acts", "voyage", "paul"],
     front="How many people were on board the ship in the storm, and how did Paul behave?",
     back="All 276 of them. Paul's commanding position was evident: out of past experience and faith in God he twice urged his shipmates to keep up their courage, and even as a prisoner did not hesitate to make known his faith in God.",
     exc="Twice the apostle urged his shipmates (all 276 of them cf. 27:37) to keep up their courage",
     scr=["2 Corinthians 11:26"]),

dict(t=2084, b=2105, kind="fact", tags=["galatians", "theme"],
     front="What is the theme of the Epistle to the Galatians, and its key word and key verse?",
     back="Theme: Justification by Faith. The key word is faith and the key verse is 3:2.",
     exc="Theme: Justification by Faith",
     scr=["Galatians 3:2"]),

dict(t=2084, b=2085, kind="fact", tags=["galatians", "preaching", "regeneration"],
     front="What does the syllabus say the local preacher finds in Galatians?",
     back="A mirror in which to look at himself or herself and at his or her message; Paul here calls Christians from legalism and good deeds to grace. Regeneration, the new birth, is the most important characteristic of a preacher.",
     exc="Note: Regeneration (new-birth) is the most important characteristic of a preacher (cf. Luke.6:39).",
     scr=[]),

dict(t=2157, b=2162, kind="definition", tags=["galatians", "law", "custodian"],
     front="What was the purpose of the Law, according to Galatians 3:23-25?",
     back="Before faith in the person and work of Christ came, Israel was under the protective custody of the Law, God shielding His people from the evil heathen rites around them. The Law served as a 'teacher', a custodian - usually a slave whose job it was to ensure the safe arrival of the child at school - and as a disciplinarian, until Christ came.",
     exc="The Law served as a \"teacher\", a custodian, usually a slave whose job it was to insure the safe arrival of the child at school.",
     scr=[]),

dict(t=2193, b=2204, kind="fact", tags=["galatians", "sowing", "stewardship"],
     front="What is God's unchangeable rule concerning sowing and reaping in Galatians 6:7-8?",
     back="'A man reaps what he sows' - each sower decides what his harvest will be. If a person spends his money to indulge the flesh he will reap a harvest that fades into oblivion; if he uses his funds to support the Lord's work he will reap a harvest that lasts forever.",
     exc="God's rule is; \"a man reaps what he sows\" and this rule is unchangeable.",
     scr=[]),

dict(t=2213, b=2227, kind="fact", tags=["galatians", "legalism", "application"],
     front="Has the problem of legalism been settled in Christianity, according to the syllabus?",
     back="No. History and experience prove otherwise: we are still confronted with the teachings that baptism, confirmation or church membership are necessary for salvation, and that the law, including keeping the Sabbath, is the believer's rule of life if they are to be saved.",
     exc="On studying the book of Galatians one might conclude that Paul had defeated the teachers of legalism so effectively that the issue would never again trouble the church. History and experience, however, prove otherwise.",
     scr=[]),

# ============================ 1 TIMOTHY ============================
dict(t=2229, b=2231, kind="person", tags=["1-timothy", "timothy"],
     front="Who was Timothy?",
     back="Paul's spiritual child, the son of a Greek father and a devout Jewish mother, Eunice. He was converted at the age of fifteen during Paul's ministry at Lystra, and from childhood had been instructed in the writings of the Old Testament.",
     exc="He was the son of a Greek father and a devout Jewish mother, Eunice (Acts 16:1; 2 Tim. 1:5). He was converted at the age of fifteen, during Paul's ministry at Lystra",
     scr=["Acts 16:1", "2 Timothy 1:5", "2 Timothy 3:15"]),

dict(t=2229, b=2245, kind="fact", tags=["1-timothy", "purpose", "key-verse"],
     front="What are the key phrase and key verse of 1 Timothy?",
     back="Key phrase: How one ought to behave in the household of God. Key verse: 3:15.",
     exc="Key phrase: How one ought to behave in the household of God",
     scr=["1 Timothy 3:15"]),

dict(t=2262, b=2269, kind="fact", tags=["1-timothy", "prayer", "rulers"],
     front="Why does Paul direct that prayer be offered for rulers?",
     back="Because of their wide influence; the object of prayer is social peace and a godly life, and certainly their salvation. He also reasons that it is for our own good that the government should be stable and the country preserved from revolution, civil war, turmoil and anarchy.",
     exc="Rulers are specially mentioned because of their wide influence. The object of prayer is social peace and godly life, and certainly for their salvation.",
     scr=[]),

dict(t=2332, b=2340, kind="fact", tags=["1-timothy", "pastoral-care", "age-groups"],
     front="How was Timothy to treat the various age-groups in the church?",
     back="As members of his own family: not rebuking an elder sharply but appealing to him as to his own father; treating other young men as brothers, older women with the respect he would give his own mother, and younger women as sisters - which would safeguard him from reproach.",
     exc="Timothy is not to rebuke an elder sharply but exhort or appeal to him as he would his own father.",
     scr=[]),

dict(t=2352, b=2362, kind="definition", tags=["1-timothy", "contentment", "godliness"],
     front="What is 'life's true gain' in 1 Timothy 6:6?",
     back="'There is a great gain in godliness with contentment.' Godliness does not give financial gain; it is a gain when accompanied by contentment. Godliness without contentment would give a one-sided testimony, and contentment without godliness would not be distinctively Christian at all.",
     exc="In verse 6, we read: \"There is a great gain in godliness with contentment\".",
     scr=[]),

# ============================ 2 TIMOTHY ============================
dict(t=2428, b=2429, kind="fact", tags=["2-timothy", "introduction"],
     front="Under what circumstances was 2 Timothy written?",
     back="Paul was in prison; it was his last letter to Timothy, and not long afterwards, according to tradition, the apostle was beheaded.",
     exc="Apostle Paul was in prison when he wrote this epistle. It was his last letter to Timothy (4:6-13). Not long afterwards, according to traditions, the apostle was beheaded.",
     scr=[]),

dict(t=2473, b=2480, kind="fact", tags=["2-timothy", "hardship", "images"],
     front="What three figures does Paul use in 2 Timothy 2:3-7 to help Timothy understand hardship?",
     back="The soldier, who should expect hardship and have the right priorities; the athlete, who should recognise the need for training and for maintaining a high standard; and the farmer, who should expect the divine blessing on his labour.",
     exc="As a soldier Timothy should expect hardship and have the right priorities; as an athlete he should recognize the need for training and of maintaining a high standard; as a farmer he should expect the divine blessing on his labour.",
     scr=["Philippians 4:13"]),

dict(t=2530, b=2531, kind="scripture", tags=["2-timothy", "paul", "crown"],
     front="How did Paul look back over his life in 2 Timothy 4:6-8?",
     back="He was already being poured out like a drink offering, and could say: I have fought the good fight, finished the race and kept the faith. He had no fear of meeting the Lord, the righteous judge, but only anticipation of a crown of righteousness waiting for him 'on that day' - a reference to Christ's return, not to Paul's death.",
     exc="I have fought the good fight (cf. 1 Tim. 6:12) finished the race (cf. Acts 20:24) and kept the faith (cf. 1 Tim. 6:10).",
     scr=["Philippians 2:17", "Numbers 28:4-7"]),

dict(t=2533, b=2544, kind="fact", tags=["2-timothy", "deliverance", "lion"],
     front="How has 'I was delivered out of the mouth of the lion' been understood?",
     back="Some see it as a general way of saying that Paul was granted a temporary delay - the trial was continued and the danger temporarily averted. Attempts have been made to identify the lion as Nero, the devil, and literal wild animals in the Roman Coliseum; others think Paul is drawing on a biblical image.",
     exc="Attempts have been made to identify the lion as Nero, the devil, and literal wild animals in",
     scr=["Psalms 22:21", "Daniel 6:22"]),

dict(t=2552, b=2557, kind="fact", tags=["2-timothy", "final-greetings"],
     front="Why did Paul urge Timothy to come to him before winter?",
     back="He may have desired his cloak before the weather turned cold, but he was more likely concerned about sailing conditions on the Adriatic Sea.",
     exc="Paul may have desired his cloak before the weather turned cold (v. 13), but he was more likely concerned about sailing conditions on the Adriatic Sea.",
     scr=[]),

]
