# -*- coding: utf-8 -*-
# Objective questions for UNIT ONE - THE GOSPEL ACCORDING TO MARK
# Each tuple-dict: t=topic anchor, b=block anchor, kind, q, opts/acc, expl, exc, scr, diff, tags

MARK = [

# ---------- Introduction (anchor 648) ----------
dict(id="NT-O-0001", t=648, b=657, kind="multiple_choice",
     q="According to the syllabus, for whom did Mark write his Gospel and where was it written?",
     opts=[("The Christians in Rome, where he wrote the Gospel", True, ""),
           ("The Jewish believers in Jerusalem, where he wrote the Gospel", False, "The syllabus places both the readers and the writing in Rome."),
           ("The churches of Galatia, written from Antioch", False, "Galatia belongs to Paul's letters, not to Mark's setting."),
           ("The Christians of Alexandria, written from Egypt", False, "Alexandria is not mentioned in connection with Mark's Gospel.")],
     expl="The summary of vital information states plainly that the Gospel was written to the Christians in Rome, where Mark wrote it.",
     exc="To Whom Written: The Christians in Rome, where he wrote the Gospel.",
     scr=[], diff="easy", tags=["mark", "introduction", "authorship"]),

dict(id="NT-O-0002", t=648, b=655, kind="multiple_choice",
     q="How do the second-century Fathers Papias and Irenaeus describe John Mark?",
     opts=[("As Peter's interpreter", True, ""),
           ("As one of the Twelve apostles", False, "The syllabus says expressly that he was not one of the Twelve apostles."),
           ("As Paul's personal physician", False, "Luke, not Mark, is the physician of the New Testament."),
           ("As the brother of Barnabas", False, "The syllabus does not describe Mark in these terms.")],
     expl="The syllabus notes that Mark was not one of the Twelve, that Peter called him his 'son', and that Papias and Irenaeus described him as Peter's interpreter.",
     exc="He was also described as Peter's interpreter by second-century Fathers Papias and Irenaeus.",
     scr=["Acts 13:13", "1 Peter 5:13"], diff="medium", tags=["mark", "authorship"]),

dict(id="NT-O-0003", t=648, b=661, kind="multiple_choice",
     q="What made the Roman Empire, as the setting of Mark's Gospel, ripe to hear the message of Jesus?",
     opts=[("Its common language and excellent transportation and communication systems", True, ""),
           ("Its official toleration of the Christian religion", False, "The syllabus says nothing of official toleration in the setting of Mark."),
           ("The collapse of emperor worship under Tiberius", False, "The syllabus mentions Tiberius only as the reigning Caesar."),
           ("The wide circulation of the Hebrew Scriptures in Rome", False, "This is not the reason the syllabus supplies.")],
     expl="The setting given for Mark is the Roman Empire under Tiberius Caesar, whose common language and communication systems allowed the message to spread quickly from nation to nation.",
     exc="The Empire, with its common language and excellent transportation and communication systems, was ripe to hear Jesus' message, which spread quickly from nation to nation.",
     scr=[], diff="medium", tags=["mark", "setting", "roman-empire"]),

# ---------- 1.1 Preparatory Events (anchor 672) ----------
dict(id="NT-O-0004", t=672, b=674, kind="multiple_choice",
     q="'Christ' is the Greek equivalent of which Hebrew title?",
     opts=[("Masiah (Messiah, Anointed)", True, ""),
           ("Joshua, that is, 'Yaweh is Salvation'", False, "Joshua is the Hebrew equivalent of the personal name 'Jesus', not of 'Christ'."),
           ("Son of God", False, "'Son of God' points to Jesus' unique relationship to God; it is not a rendering of 'Christ'."),
           ("Son of Man", False, "The syllabus links 'Son of Man' with Jesus' full humanity, not with the title 'Christ'.")],
     expl="The syllabus distinguishes 'Jesus', His divinely given personal name whose Hebrew equivalent is 'Joshua', from 'Christ', the Greek equivalent of the Hebrew title Masiah.",
     exc="\"Christ\" is the Greek equivalent of the Hebrew title Masiah (Messiah, Anointed).",
     scr=["Luke 1:31"], diff="easy", tags=["mark", "titles-of-jesus", "greek-terms"]),

# ---------- Chapter 1 (anchor 679) ----------
dict(id="NT-O-0005", t=679, b=682, kind="multiple_response",
     q="Which THREE preparatory events does Mark present in the brief passage of 1:2-13?",
     opts=[("The ministry of John the Baptist", True, ""),
           ("Jesus' baptism", True, ""),
           ("Jesus' temptation", True, ""),
           ("The calling of the first disciples", False, "The call of the first disciples belongs to Jesus' public ministry in Galilee, not to the preparatory events."),
           ("The cleansing of a leper", False, "The cleansing of the leper comes later, in the account of Jesus' authority over disease.")],
     expl="Mark compresses three preparatory events into 1:2-13: John's ministry, Jesus' baptism and Jesus' temptation.",
     exc="Three preparatory events are presented in this brief passage: (i) the ministry of John the Baptist (vs. 2-8) (ii) Jesus' baptism (vs. 9-11) (iii) Jesus' temptation (vs. 12-13).",
     scr=[], diff="easy", tags=["mark", "john-the-baptist", "baptism", "temptation"]),

dict(id="NT-O-0006", t=679, b=698, kind="true_false",
     q="The reference to wild animals during Jesus' temptation is recorded only in Mark.",
     ans=True,
     expl="The syllabus states that this detail is peculiar to Mark, and explains it from the Old Testament imagery of the wilderness as a place of desolation, loneliness and danger.",
     exc="The reference to wild animals during Jesus' temptation is recorded only in Mark.",
     scr=["Isaiah 13:20-22", "Psalms 91:11-13"], diff="easy", tags=["mark", "temptation", "wilderness"]),

dict(id="NT-O-0007", t=679, b=687, kind="multiple_choice",
     q="What does the syllabus say is seen at the baptism of Jesus in Mark 1:9-11?",
     opts=[("All three members of the Trinity together - the Father, Son and Holy Spirit", True, ""),
           ("The first public confession of Jesus by a demon", False, "The demonic recognition of Jesus comes later, in the synagogue at Capernaum."),
           ("The commissioning of the Twelve apostles", False, "The Twelve are chosen much later, in chapter 3."),
           ("The first prediction of the passion", False, "The first passion prediction comes at Caesarea Philippi in 8:31.")],
     expl="The Spirit descending dovelike and the Father's voice from heaven, together with Jesus Himself, bring all three Persons of the Trinity together in the baptism scene.",
     exc="Here we see all three members of the Trinity together – the Father, Son and Holy Spirit.",
     scr=[], diff="medium", tags=["mark", "baptism", "trinity"]),

# ---------- 1.2 Jesus' Public Ministry in Galilee (anchor 700) ----------
dict(id="NT-O-0008", t=700, b=720, kind="multiple_choice",
     q="With whose authority did the crowds at Capernaum contrast the authority affirmed in Jesus' teaching?",
     opts=[("The teachers of the Law (Scribes)", True, ""),
           ("The Sadducees of the temple party", False, "The Sadducees do not appear in Mark until the question about the resurrection in chapter 12."),
           ("The Herodians", False, "The Herodians appear as political supporters of Herod Antipas, not as teachers of the Law."),
           ("The priests of the temple", False, "The comparison drawn in verse 22 is with the Scribes.")],
     expl="Because the Scribes merely quoted the sayings of their predecessors, the people sensed in Jesus' manner an authority beyond any they were accustomed to.",
     exc="In verse 22, the crowds contrast the authority affirmed in His teaching with the teachers of the Law (Scribes).",
     scr=[], diff="medium", tags=["mark", "authority", "scribes"]),

dict(id="NT-O-0009", t=700, b=739, kind="true_false",
     q="The syllabus states that the Rabbis regarded leprosy as humanly incurable, and that the Old Testament records only two occasions on which God cleansed a leper.",
     ans=True,
     expl="The two Old Testament occasions cited are Numbers 12:10-15 and 2 Kings 5:1-14; against that background the leper's conviction that Jesus could cure him is remarkable.",
     exc="The Rabbis regarded leprosy as humanly incurable. Only on two occasions does the Old Testament record that God cleansed a leper",
     scr=["Numbers 12:10-15", "2 Kings 5:1-14"], diff="medium", tags=["mark", "leprosy", "miracles"]),

dict(id="NT-O-0010", t=700, b=731, kind="multiple_choice",
     q="On how many crucial occasions does Mark selectively portray Jesus at prayer, and in what kind of setting?",
     opts=[("Three occasions, each in a setting of darkness and aloneness", True, ""),
           ("Two occasions, each in the synagogue at Capernaum", False, "The syllabus names three occasions, not two, and none of them is in a synagogue."),
           ("Seven occasions, each before a miracle", False, "No such pattern is given in the syllabus."),
           ("Three occasions, each in the temple at Jerusalem", False, "The settings given are the desert, the mountain and Gethsemane, not the temple.")],
     expl="Mark places Jesus at prayer near the beginning (1:35), near the middle (6:46) and near the end (14:32-42) of his account, each time in darkness and aloneness, and each time when facing His messianic mission.",
     exc="Mark selectively portrayed Jesus at prayer on three crucial occasions, each in a setting of darkness and aloneness:",
     scr=[], diff="hard", tags=["mark", "prayer", "structure"]),

dict(id="NT-O-0011", t=700, b=708, kind="multiple_choice",
     q="In Jesus' first preaching, what does 'the kingdom of God' mean according to the syllabus?",
     opts=[("The rule of God", True, ""),
           ("The restored political kingdom of Israel", False, "That was the disciples' misunderstanding; the syllabus defines the phrase as the rule of God."),
           ("The company of the Twelve apostles", False, "The Twelve are not identified with the kingdom in this passage."),
           ("The temple and its worship", False, "The syllabus gives no such definition.")],
     expl="Jesus' message signifies that God has begun to establish His rule in a world many religious Jews viewed as under the tyranny of Satan and evil.",
     exc="\"The kingdom of God\" here means the rule of God",
     scr=[], diff="medium", tags=["mark", "kingdom-of-god", "preaching"]),

# ---------- Chapter 2 (anchor 743) ----------
dict(id="NT-O-0012", t=743, b=762, kind="multiple_choice",
     q="With whom is Levi, called by Jesus at the tax office, identified in Matthew 9:9, and what was his occupation?",
     opts=[("Matthew, a customs official in the service of Herod Antipas", True, ""),
           ("Nathanael, a scribe in the service of the Sanhedrin", False, "Nathanael is not mentioned in Mark's account of the call of Levi."),
           ("Zacchaeus, a chief tax collector at Jericho", False, "Zacchaeus does not appear in Mark's Gospel."),
           ("Simon the Zealot, a collector of the temple tax", False, "Simon the Zealot is listed among the Twelve, but he is not Levi.")],
     expl="The syllabus identifies Levi with Matthew and describes him as a customs official under Herod Antipas who responded to Jesus' call immediately.",
     exc="Levi is identified in Mt. 9:9 with Matthew, a customs official in the service of Herod Antipas.",
     scr=[], diff="easy", tags=["mark", "call-of-levi", "disciples"]),

dict(id="NT-O-0013", t=743, b=767, kind="fill_blank",
     q="Complete the syllabus definition: 'the word sinner is a technical term for common people regarded by the Pharisees as ____________'.",
     acc=["untaught in the Law", "untaught in the law", "untaught in the Law; who did not abide by rigid pharisaic standards"],
     expl="For the Pharisees a 'sinner' was one untaught in the Law who did not abide by rigid pharisaic standards - which is why Jesus' eating with such people gave offence.",
     exc="The word sinner is a technical term for common people regarded by the Pharisees as untaught in the Law; who did not abide by rigid pharisaic standards.",
     scr=[], diff="medium", tags=["mark", "pharisees", "terms"]),

dict(id="NT-O-0014", t=743, b=785, kind="multiple_choice",
     q="Under Mosaic Law a hungry traveller might pluck and eat corn from another person's field on one condition. What was it?",
     opts=[("That he used only his hands for the purpose and not a sickle", True, ""),
           ("That he first obtained the owner's permission", False, "The syllabus mentions no such requirement."),
           ("That he did so only outside the Sabbath year", False, "The Sabbath year is not the issue raised in this passage."),
           ("That he left payment at the edge of the field", False, "No payment is mentioned in the syllabus's account.")],
     expl="Deuteronomy 23:25 permitted plucking by hand; the scribes, however, regarded the practice technically as reaping and so forbade it on the Sabbath.",
     exc="Mosaic Law permitted a hungry traveller to pluck and eat corn from another person's field, so long as he only used his hands for the purpose, not a sickle",
     scr=["Deuteronomy 23:25", "Exodus 34:21"], diff="medium", tags=["mark", "sabbath", "mosaic-law"]),

dict(id="NT-O-0015", t=743, b=759, kind="multiple_choice",
     q="What distinction does the syllabus draw between the titles 'Son of Man' and 'Son of God'?",
     opts=[("'Son of Man' emphasises that Jesus is fully human, while 'Son of God' emphasises deity", True, ""),
           ("'Son of Man' emphasises deity, while 'Son of God' emphasises His messianic office", False, "The syllabus reverses this: 'Son of Man' emphasises His full humanity."),
           ("Both titles refer only to Jesus' earthly ministry", False, "The syllabus links 'Son of God' expressly with His deity."),
           ("'Son of Man' was a title used only by the Scribes", False, "In this passage Jesus applies the title to Himself.")],
     expl="As God's Son, Jesus has authority to forgive sin; as a man He can identify with our deepest sufferings and help us overcome sin.",
     exc="The title \"Son of man\" emphasizes that Jesus is fully human, while son of God emphasizes deity, i.e. He is fully God.",
     scr=[], diff="medium", tags=["mark", "titles-of-jesus", "christology"]),

# ---------- Chapter 3 (anchor 795) ----------
dict(id="NT-O-0016", t=795, b=803, kind="multiple_choice",
     q="What did 'hardness' of heart connote to the Hebrew, as distinct from the modern sense of callousness or cruelty?",
     opts=[("Unteachableness, a stubborn resistance to the purpose of God", True, ""),
           ("Physical infirmity of the body", False, "The term is used morally and spiritually, not physically."),
           ("Ignorance of the written Law", False, "The syllabus speaks of stubborn resistance, not mere ignorance."),
           ("Grief and sorrow of spirit", False, "Grief was Jesus' response to their hardness, not the meaning of the word.")],
     expl="The Pharisees' refusal to debate the moral question of doing good on the Sabbath illustrates precisely this unteachable, stubborn resistance to God's purpose.",
     exc="Hardness (hard-hearted), to us means callousness or cruel, but here (i.e. to the Hebrew) it connotes unteachableness, a stubborn resistance to the purpose of God.",
     scr=[], diff="medium", tags=["mark", "hebrew-terms", "sabbath"]),

dict(id="NT-O-0017", t=795, b=817, kind="multiple_choice",
     q="Which list gives the five fishermen among the Twelve as named in the syllabus?",
     opts=[("Peter, James, John, Andrew and Philip", True, ""),
           ("Peter, James, John, Andrew and Thomas", False, "Thomas is not named among the fishermen in the syllabus's list."),
           ("Peter, Andrew, Philip, Bartholomew and Thaddaeus", False, "Only Peter, Andrew and Philip belong to the list of fishermen."),
           ("Peter, James, John, Levi and Judas", False, "Levi was a publican and Judas hailed from Kerith in Judah.")],
     expl="The syllabus notes that five of the Twelve were fishermen, one a publican and one a zealot, and that all were Galileans except Judas, who came from Kerith in Judah.",
     exc="The five fishermen among the Twelve were: (1) Peter (2) James (3) John (4) Andrew (5) Philip.",
     scr=[], diff="medium", tags=["mark", "the-twelve", "disciples"]),

dict(id="NT-O-0018", t=795, b=808, kind="true_false",
     q="According to the syllabus, Jesus welcomed the repeated cries of recognition from the evil spirits because their statements about Him were true.",
     ans=False,
     expl="Though their statements were true, Jesus ordered them not to tell who He was, apparently because the gospel would be damaged by an association with demon-possessed people; He wanted men to find out who He was by His words and deeds.",
     exc="Jesus did not accept their repeated cries of recognition, and ordered them not to tell who He was",
     scr=[], diff="medium", tags=["mark", "messianic-secret", "demons"]),

# ---------- Chapter 4 (anchor 829) ----------
dict(id="NT-O-0019", t=829, b=835, kind="multiple_choice",
     q="According to the syllabus, why did Jesus teach in parables?",
     opts=[("In order to test the spiritual responsiveness of His audience", True, ""),
           ("In order to conceal His messiahship from the Romans", False, "No political motive is given in the syllabus."),
           ("Because the crowds could not read the written Law", False, "Literacy is not the reason offered."),
           ("Because the Scribes had forbidden direct teaching in the synagogue", False, "The syllabus gives no such prohibition.")],
     expl="Those provoked by the parables into intensive reflection could obtain enlightenment; those who would not reflect would be ever seeing but never perceiving.",
     exc="The essence of His reply seems to be that He did so in order to test the spiritual responsiveness of His audience.",
     scr=[], diff="medium", tags=["mark", "parables", "teaching-method"]),

dict(id="NT-O-0020", t=829, b=857, kind="multiple_choice",
     q="In the parable of the mustard seed, what is the preferred view of the birds of the air which rested in the shade of the shrub?",
     opts=[("They depict the incorporation of the Gentiles into God's kingdom programme", True, ""),
           ("They depict Satan snatching away the word", False, "The birds stand for Satan in the parable of the sower, not in the parable of the mustard seed."),
           ("They depict the Twelve apostles", False, "The syllabus does not identify the birds with the apostles."),
           ("They depict the false teachers who corrupt the church", False, "This interpretation is not offered in the syllabus.")],
     expl="Although the parable may be viewed simply as showing the expansion of the kingdom from insignificant beginnings, the syllabus states that the incorporation of the Gentiles is the preferred view.",
     exc="The incorporation of the Gentiles into God's kingdom programme is a preferred view.",
     scr=["Daniel 4:21"], diff="hard", tags=["mark", "parables", "gentiles"]),

dict(id="NT-O-0021", t=829, b=851, kind="multiple_choice",
     q="In the parable of the seed growing secretly, to what is outside instrumentality limited?",
     opts=[("To sowing and reaping", True, ""),
           ("To watering and weeding", False, "These are not mentioned in the syllabus's exposition of the parable."),
           ("To ploughing and threshing", False, "The syllabus names only the two activities that begin and end the process."),
           ("To preaching and baptising", False, "The parable is explained agriculturally, not sacramentally.")],
     expl="Between the initial and final activities lies confidence in the vitality of the seed - that is, the word of God will do its own work in human hearts if given the opportunity.",
     exc="Its emphasis is upon the fact that the word of God will do its own work in human hearts if given the opportunity, in exactly the same way as the earth produces of itself.",
     scr=["John 4:35,38"], diff="medium", tags=["mark", "parables", "word-of-god"]),

# ---------- Chapter 5 (anchor 869) ----------
dict(id="NT-O-0022", t=869, b=885, kind="fill_blank",
     q="When Jesus asked the demon-possessed man of the Gerasene country his name, he replied, 'My name is ____________ for we are many.'",
     acc=["Legion", "legion"],
     expl="Many evil powers controlled the man and tormented him as one combined force under the leadership of one demon as their spokesman, which explains the alternating singular and plural pronouns.",
     exc="\"my name is Legion for we are many\" - the man replied.",
     scr=[], diff="easy", tags=["mark", "demons", "miracles"]),

dict(id="NT-O-0023", t=869, b=889, kind="true_false",
     q="The account of the raising of Jairus' daughter is broken by the incident of the woman with the issue of blood, giving the section a 'sandwich' structure.",
     ans=True,
     expl="What appeared to be a disastrous delay in fact assured the restoration of Jairus' daughter, as if it were providentially ordered to test and strengthen Jairus' faith.",
     exc="This section has a \"sandwich\" structure.",
     scr=[], diff="easy", tags=["mark", "structure", "miracles"]),

dict(id="NT-O-0024", t=869, b=876, kind="multiple_choice",
     q="What does the uncontrollable behaviour of the demoniac show, according to the syllabus?",
     opts=[("That demon possession is a desperate satanic attempt to distort and destroy God's image in man", True, ""),
           ("That demon possession is only a form of insanity", False, "The syllabus expressly denies that it is a mere ailment or insanity."),
           ("That the man had committed some particular sin", False, "No such connection is drawn in this passage."),
           ("That the man was possessed by the spirit of a dead person", False, "The syllabus offers no such explanation.")],
     expl="The syllabus insists that such behaviour is not a mere ailment or insanity but a satanic assault upon the image of God in man.",
     exc="Such behaviour shows clearly that demon possession is not a mere ailment or insanity but",
     scr=["James 2:19"], diff="medium", tags=["mark", "demons", "doctrine"]),

# ---------- Chapter 6 (anchor 899) ----------
dict(id="NT-O-0025", t=899, b=907, kind="multiple_choice",
     q="For what reasons were the Twelve sent out two by two?",
     opts=[("For legal reasons, for the sake of witness, and for fellowship", True, ""),
           ("For safety on the roads and to save expense", False, "Neither safety nor economy is given as a reason in the syllabus."),
           ("So that one might preach while the other healed", False, "The syllabus describes a threefold ministry shared by all of them."),
           ("To fulfil a Roman regulation on travelling teachers", False, "The legal reason given rests on Old Testament witness law, not Roman regulation.")],
     expl="The practice of going two by two was common, was required for legal purposes of testimony, and served both witness and fellowship.",
     exc="The Twelve sent out two by two, was a common practice which was for legal reasons (cf. 11:1; 14:13; John 8;17; Dt. 17:6; 19:15) also for the sake of witness (2 Cor. 13:1), and fellowship.",
     scr=["2 Corinthians 13:1"], diff="medium", tags=["mark", "mission-of-the-twelve"]),

dict(id="NT-O-0026", t=899, b=925, kind="fill_blank",
     q="Mark 6:30 is the only place in this Gospel where the Twelve are called ____________.",
     acc=["apostles", "apostle", "the apostles"],
     expl="The syllabus notes that it is here and here only in Mark that the Twelve are given the title 'apostles'.",
     exc="It is here and here only in this Gospel that the Twelve are called apostles",
     scr=[], diff="medium", tags=["mark", "the-twelve", "terms"]),

dict(id="NT-O-0027", t=899, b=922, kind="multiple_choice",
     q="On what grounds had John the Baptist protested against Herod's marriage, and with what result?",
     opts=[("Presumably on the grounds of Leviticus 18:16 and 20:21, against Herod's marriage to Herodias his brother Philip's wife; for this Herod imprisoned him", True, ""),
           ("On the grounds that Herodias was a Gentile; for this he was banished", False, "The objection was not to her nationality, and John was imprisoned, not banished."),
           ("On the grounds that Herod had divorced his first wife; for this he was flogged", False, "The syllabus gives imprisonment, not flogging, as the outcome."),
           ("On the grounds that Herod had built a pagan temple; for this he was beheaded at once", False, "The beheading followed later, at the scheming of Herodias.")],
     expl="Herodias, not satisfied with John's mere imprisonment, schemed to have him killed.",
     exc="John the Baptist had protested, presumably on the grounds of Leviticus18:16 and 20:21, against Herod's marriage to Herodias, his brother Philip's wife (v. 17).",
     scr=[], diff="medium", tags=["mark", "john-the-baptist", "herod"]),

dict(id="NT-O-0028", t=899, b=933, kind="multiple_choice",
     q="According to the disciples' calculations, what would feeding the crowd of five thousand have cost?",
     opts=[("Literally 200 denarii, roughly eight months of a worker's wages", True, ""),
           ("Fifty denarii, about a month's wages", False, "The syllabus gives 200 denarii, roughly eight months of a worker's wages."),
           ("A talent of silver", False, "No such sum is mentioned in the syllabus."),
           ("Thirty pieces of silver", False, "That sum belongs to the betrayal narrative, not to the feeding of the five thousand.")],
     expl="The sum was far beyond the disciples' means, which is why Jesus' command that they themselves feed the crowd was a challenge to faith.",
     exc="According to their calculations, feeding such a crowd would take, literally 200 denarii. This is roughly equivalent to eight months of a worker's wages, an amount beyond their means.",
     scr=[], diff="medium", tags=["mark", "miracles", "feeding-five-thousand"]),

# ---------- Chapter 7 (anchor 952) ----------
dict(id="NT-O-0029", t=952, b=966, kind="multiple_choice",
     q="By declaring his possessions 'Corban', from which commandment could a person absolve himself?",
     opts=[("The fifth commandment, which enjoins respect to parents", True, ""),
           ("The fourth commandment, on keeping the Sabbath", False, "Restrictive Sabbath rules are cited as a further example, but the Corban vow concerned the fifth commandment."),
           ("The eighth commandment, against stealing", False, "The syllabus links Corban with duty to parents."),
           ("The tenth commandment, against covetousness", False, "Covetousness is discussed in chapter 10, not in the Corban tradition.")],
     expl="The Corban vow is offered as one example among many of scribal traditions which distorted and obscured the Old Testament.",
     exc="In their tradition, it was possible for a person to declare all his possessions to be Corban and thereby absolve oneself from the fifth commandment which enjoins respect to parents.",
     scr=["Numbers 30:1-16"], diff="hard", tags=["mark", "corban", "tradition"]),

dict(id="NT-O-0030", t=952, b=984, kind="true_false",
     q="The cure of the Syro-Phoenician woman's daughter is the only miracle in Mark which Jesus performed without setting eyes on the sick person and without giving any vocal command.",
     ans=True,
     expl="It was the woman's demonstration of humility and faith that moved Jesus to assure her, at a distance, that her daughter was cured.",
     exc="This miracle is the only one in the book of Mark that Jesus performed without even setting eyes on the sick person and without giving any vocal command.",
     scr=[], diff="medium", tags=["mark", "miracles", "gentiles"]),

dict(id="NT-O-0031", t=952, b=972, kind="multiple_choice",
     q="What, positively stated, is the true source of defilement according to Jesus' explanation in Mark 7:14-23?",
     opts=[("What comes out of a man - that is, what he thinks in his heart", True, ""),
           ("What a man eats with unwashed hands", False, "This is precisely what Jesus set aside; a man is not defiled morally by what he eats."),
           ("Contact with Gentiles and their food", False, "The syllabus says Jesus set aside the whole idea that certain foods make a person unclean."),
           ("Failure to observe the tradition of the elders", False, "Jesus rejected that supplementary legislation as of human origin.")],
     expl="Jesus spoke in a moral sense: a person is defiled by what he thinks in his heart even though he may scrupulously observe outward rituals of hygiene.",
     exc="Positively what comes out of a man makes him \"unclean\".",
     scr=[], diff="medium", tags=["mark", "defilement", "teaching"]),

# ---------- Chapter 8 (anchor 989) ----------
dict(id="NT-O-0032", t=989, b=1004, kind="multiple_choice",
     q="Why could the seven basketfuls left over at the feeding of the four thousand hold more than the twelve basketfuls of Mark 6:43?",
     opts=[("They were probably rope or mat baskets, sometimes large enough to carry an adult", True, ""),
           ("They were temple measures used for grain offerings", False, "No cultic measure is mentioned in the syllabus."),
           ("They were the large baskets used by Roman soldiers", False, "The syllabus makes no reference to Roman baskets."),
           ("They were seven times the size of an ordinary basket", False, "The difference lies in the kind of basket, not in a fixed multiple.")],
     expl="The syllabus draws attention to the different Greek words for basket, comparing the large rope or mat basket of Acts 9:25 in which a man could be carried.",
     exc="they were probably rope or mat baskets, sometimes large enough to carry an adult.",
     scr=["Acts 9:25"], diff="hard", tags=["mark", "miracles", "feeding-four-thousand"]),

dict(id="NT-O-0033", t=989, b=1009, kind="multiple_choice",
     q="What were the Pharisees really demanding when they sought from Jesus 'a sign from heaven'?",
     opts=[("That Jesus give unmistakable proof that He and His mission were authorised by God", True, ""),
           ("That Jesus perform a spectacular miracle for the entertainment of the crowd", False, "The syllabus says they were not necessarily demanding a spectacular miracle."),
           ("That Jesus repeat the feeding of the four thousand", False, "No such demand is recorded in the syllabus."),
           ("That Jesus declare openly whether He would pay the temple tax", False, "That question belongs to a different controversy.")],
     expl="Their demand arose out of unbelief - in fact they believed the opposite - and Jesus rejected it, departing evidently out of indignation.",
     exc="They were not necessarily demanding a spectacular miracle, but that Jesus give unmistakable proof that He and His mission were authorized by God.",
     scr=[], diff="medium", tags=["mark", "pharisees", "signs"]),

# ---------- 1.3 From Galilee to Jerusalem (anchor 1021) ----------
dict(id="NT-O-0034", t=1021, b=1034, kind="multiple_choice",
     q="What was the main task of Jesus in undertaking the journey from Galilee to Jerusalem?",
     opts=[("To prepare His disciples for His impending crucifixion", True, ""),
           ("To confront the Sanhedrin in open debate", False, "The confrontations in Jerusalem follow; they are not the purpose of the journey."),
           ("To carry the gospel to the Gentile cities of the Decapolis", False, "The Decapolis ministry belongs to an earlier stage."),
           ("To keep the Feast of Tabernacles at the temple", False, "The syllabus makes no reference to that feast.")],
     expl="On this journey Jesus explained the nature of His messianic vocation and its implications for those who choose to follow Him, with three definite predictions of the passion.",
     exc="The main task of Jesus in undertaking this journey from Galilee to Jerusalem was to prepare His disciples for His impending crucifixion.",
     scr=["Isaiah 53"], diff="easy", tags=["mark", "passion-predictions", "discipleship"]),

# ---------- Chapter 9 (anchor 1040) ----------
dict(id="NT-O-0035", t=1040, b=1046, kind="multiple_choice",
     q="Four interpretations have been suggested for the promise of Mark 9:1 that some standing there would not taste death until they saw the kingdom of God. Which does the syllabus regard as most reasonable in this context?",
     opts=[("The transfiguration", True, ""),
           ("The destruction of Jerusalem in AD 70", False, "This is listed as one of the four possibilities but is not the preferred view."),
           ("Pentecost and the beginning of missionary enterprise", False, "This too is listed, but the syllabus prefers the transfiguration."),
           ("The resurrection and ascension", False, "Again a listed possibility, but not the one the syllabus judges most reasonable.")],
     expl="The specific reference in the following account of the transfiguration (9:2a) indicates that Mark understood a definite connection between the prediction and that event.",
     exc="The transfiguration is the most reasonable view in this context.",
     scr=["2 Peter 1:16-19"], diff="hard", tags=["mark", "transfiguration", "kingdom-of-god"]),

dict(id="NT-O-0036", t=1040, b=1049, kind="multiple_choice",
     q="What does the word 'transfigured' mean, according to the syllabus?",
     opts=[("'To be changed into another form', not just a change in outward appearance", True, ""),
           ("To be clothed in a garment of white light", False, "The syllabus defines the term as an inward change of form, not a change of clothing."),
           ("To be lifted up bodily into heaven", False, "That describes the ascension, not the transfiguration."),
           ("To be temporarily hidden from human sight", False, "No such meaning is given.")],
     expl="Jesus' human body was transformed, or glorified, and this impressed on the three disciples what He will be when He returns visibly in power and glory.",
     exc="\"Transfigured\" means \"to be changed into another form\", not just a",
     scr=["2 Peter 1:16"], diff="medium", tags=["mark", "transfiguration", "greek-terms"]),

dict(id="NT-O-0037", t=1040, b=1055, kind="true_false",
     q="Jesus taught that Elijah had already come in John the Baptist but had not been recognised.",
     ans=True,
     expl="The disciples were correct about Elijah, but their concept of the Son of Man was deficient because it did not include the truths of His suffering and death.",
     exc="Christ then adds (Mk 9:13) that Elijah had already come in John the Baptist but had not been recognized.",
     scr=["Malachi 4:5-6"], diff="medium", tags=["mark", "elijah", "john-the-baptist"]),

dict(id="NT-O-0038", t=1040, b=1079, kind="multiple_response",
     q="In the lessons on discipleship of Mark 9:43-50, which THREE organs does the syllabus name as symbols of various types of activity?",
     opts=[("The hand that snatches for things it should not", True, ""),
           ("The foot that goes where it ought not", True, ""),
           ("The eye that desires what it ought not", True, ""),
           ("The ear that listens to what it ought not", False, "The ear is not among the organs mentioned in this passage."),
           ("The tongue that speaks what it ought not", False, "The tongue is not listed here; it belongs to the healing of the deaf and dumb man in chapter 7.")],
     expl="The hyperboles are not to be pressed literally; the point is that participation in the kingdom of God is worth any sacrifice, and that a disciple must take prompt, decisive action against whatever would draw him away.",
     exc="The organs mentioned here are really symbols for various types of activity, for example, (1) the hand that snatches for things it should not, (2) the foot that goes where it ought not; (3) the eye that desires what it ought not.",
     scr=[], diff="medium", tags=["mark", "discipleship", "hyperbole"]),

# ---------- Chapter 10 (anchor 1081) ----------
dict(id="NT-O-0039", t=1081, b=1083, kind="multiple_choice",
     q="What was the difference between the schools of Shammai and Hillel on the question of divorce?",
     opts=[("Shammai held the marriage bond indissoluble except for the wife's infidelity, while Hillel allowed divorce for almost any cause", True, ""),
           ("Shammai allowed divorce for almost any cause, while Hillel held the bond indissoluble", False, "The positions are the other way round: Shammai was the strict school."),
           ("Both schools forbade divorce absolutely", False, "Both permitted divorce; they differed over the grounds."),
           ("Shammai forbade divorce but permitted separation, while Hillel forbade both", False, "This distinction is not made in the syllabus.")],
     expl="Jesus replied first that Moses' legislation was a concession to human weakness, and then took the questioners back beyond Moses to God's ideal at creation.",
     exc="The school of Shammai maintained the strict interpretation of this, that the marriage band was indissoluble except in the event of the wife's infidelity. The school of Hillel took the liberal view allowing divorce for almost any cause (v. 5).",
     scr=[], diff="hard", tags=["mark", "marriage", "divorce", "rabbinic-schools"]),

dict(id="NT-O-0040", t=1081, b=1091, kind="multiple_choice",
     q="Which command in Jesus' list to the rich man occurs only in Mark, and how is it interpreted?",
     opts=[("'Do not defraud', interpreted as 'Do not covet'", True, ""),
           ("'Do not bear false witness', interpreted as 'Do not slander'", False, "That commandment is not peculiar to Mark's list."),
           ("'Honour your father and mother', interpreted as 'Do not use Corban'", False, "Corban belongs to the discussion of tradition in chapter 7."),
           ("'You shall have no other gods', interpreted as 'Do not love money'", False, "The first commandment is invoked in the exposition, but it is not the command peculiar to Mark.")],
     expl="Jesus quoted commandments dealing with human relationships that are more easily verified in a person's conduct; the one necessary thing the rich man lacked was unrivalled allegiance to God, since wealth was his god.",
     exc="The command Do not defraud occurring only in Mark is interpreted \"Do not covet\"",
     scr=["Exodus 20:3"], diff="hard", tags=["mark", "rich-young-man", "commandments"]),

dict(id="NT-O-0041", t=1081, b=1101, kind="multiple_choice",
     q="Why is Bartimaeus' use of the title 'son of David' significant in Mark?",
     opts=[("It occurs here for the first time in Mark and designated the Messiah as David's descendant", True, ""),
           ("It was the customary greeting given to any rabbi in Jericho", False, "The syllabus says the bystanders may have objected precisely to this address."),
           ("It was a title reserved for the reigning high priest", False, "The title belongs to the Messiah as David's descendant."),
           ("It showed that Bartimaeus regarded Jesus merely as a prophet", False, "It shows rather that he believed Jesus of Nazareth was Israel's Messiah.")],
     expl="Despite his physical blindness Bartimaeus believed Jesus was Israel's Messiah, in contrast with the blind unbelief of most Jews; Jesus did not silence him, implying He accepted the title.",
     exc="They might have been opposed to him addressing Jesus as son of David (occurring here for the first time in Mark) which designated the Messiah as David's descendant.",
     scr=["Isaiah 61:1"], diff="hard", tags=["mark", "bartimaeus", "titles-of-jesus"]),

# ---------- 2.1 The Entry into Jerusalem (anchor 1107) ----------
dict(id="NT-O-0042", t=1107, b=1108, kind="multiple_choice",
     q="By entering Jerusalem mounted on a colt, Jesus made a claim that which prophecy applied to Him?",
     opts=[("Zechariah 9:9", True, ""),
           ("Isaiah 53:7", False, "Isaiah 53 is cited elsewhere for the suffering of the Son of Man, not for the entry."),
           ("Psalm 118:25", False, "Psalm 118:25 lies behind the crowd's cry 'Hosanna', not behind the choice of the colt."),
           ("Malachi 4:5", False, "Malachi 4:5 concerns the coming of Elijah.")],
     expl="Jesus chose an animal never ridden before, in accordance with the prophet's description of a new colt, and used a donkey rather than a horse to show that He would not fulfil His messianic office as a warrior.",
     exc="Jesus decided to do so by an act which constituted a claim that the prophecy of Zechariah 9:9 applied to Him.",
     scr=["Zechariah 9:9"], diff="medium", tags=["mark", "triumphal-entry", "prophecy"]),

dict(id="NT-O-0043", t=1107, b=1108, kind="fill_blank",
     q="The word 'Hosanna', which the crowd cried out at the entry into Jerusalem, is derived from the Hebrew exclamation ____________, as written in Psalm 118:25.",
     acc=["save now", "'save now'", "Save now"],
     expl="The syllabus suggests it may have been an appeal to God to save the nation Israel now that the Messiah had appeared among them.",
     exc="The word \"Hosanna\" (v. 9) which the crowd cried out, is derived from the Hebrew exclamation 'save now', as is written in Ps. 118: 25.",
     scr=["Psalms 118:25"], diff="medium", tags=["mark", "triumphal-entry", "hebrew-terms"]),

# ---------- 2.2 Beginnings of Conflict (anchor 1110) ----------
dict(id="NT-O-0044", t=1110, b=1116, kind="multiple_choice",
     q="Why was the appearance of the fig tree deceptive, and of what did Jesus make it a symbol?",
     opts=[("Its leaves promised fruit which was absent; it became a symbol of the Temple, which had the appearance of dedication to God but fell short of doing His will", True, ""),
           ("It was out of season, so Jesus used it to teach patience in prayer", False, "The syllabus does use the withered tree to teach faith, but the deceptive appearance points to the Temple."),
           ("It was planted by the roadside, so Jesus used it to teach against private ownership", False, "No such lesson is drawn."),
           ("It bore fruit without leaves, so Jesus used it as a symbol of hidden faith", False, "The reverse is the case: it bore leaves without fruit.")],
     expl="In Palestine fig trees produced small edible buds in March before the large green leaves of early April; leaves without those buds meant the tree's appearance was deceptive.",
     exc="the tree's leaves promised fruit; the absence of the green fruits, therefore, meant that the tree's appearance was deceptive. It is this that Jesus uses as a symbol for the Temple.",
     scr=[], diff="hard", tags=["mark", "fig-tree", "temple", "judgment"]),

dict(id="NT-O-0045", t=1110, b=1113, kind="true_false",
     q="Both the cursing of the barren fig tree and the cleansing of the Temple signify God's impending judgment on Israel for religious hypocrisy.",
     ans=True,
     expl="This is another example of Mark's sandwiching of two stories together so that each episode helps explain the other.",
     exc="Both episodes signify God's impending judgment on Israel for religious hypocrisy.",
     scr=[], diff="medium", tags=["mark", "structure", "judgment"]),

dict(id="NT-O-0046", t=1110, b=1129, kind="multiple_choice",
     q="When the representatives of the Sanhedrin challenged Jesus' authority, what two questions did they ask?",
     opts=[("What was the nature of His authority, and who was the source of His authority", True, ""),
           ("Whether He was the Messiah, and whether He would destroy the temple", False, "Those questions belong to the trial before the Sanhedrin."),
           ("Whether it was lawful to pay tax to Caesar, and whose wife the woman would be", False, "Those are the later questions of the Pharisees and Sadducees."),
           ("Where He was born, and by which rabbi He had been taught", False, "No such questions are recorded in the syllabus.")],
     expl="Jesus replied by asking whether John the Baptist had ministered by divine appointment or by human commission; being caught in a dilemma they declined to answer, and He therefore refused to answer theirs.",
     exc="As guardians of Israel's religious life, they asked two questions: (1) what was the nature of his authority (cf. 1:22, 27) i.e., what were His credentials; (2) who was the source of his authority.",
     scr=[], diff="medium", tags=["mark", "authority", "sanhedrin"]),

# ---------- Chapter 12 (anchor 1131) ----------
dict(id="NT-O-0047", t=1131, b=1138, kind="multiple_choice",
     q="What did the Sadducees deny, in contrast with the Pharisees?",
     opts=[("The resurrection, future judgment, and the existence of angels and spirits", True, ""),
           ("The authority of the Pentateuch and the levirate marriage law", False, "They appealed to the Pentateuch and quoted the levirate law; they did not deny them."),
           ("The Davidic descent of the Messiah", False, "That question is raised by Jesus Himself, not by the Sadducees."),
           ("The obligation to pay the poll tax to Caesar", False, "The tax question was put by the Pharisees and Herodians.")],
     expl="The Sadducees, generally believed to be Jewish aristocrats, denied all three; the Pharisees acknowledged them all.",
     exc="The Sadducees (generally believed to be Jewish aristocrats) denied the truth of the resurrection, future judgment, and existence of angels and spirits (Acts 23:6-8).",
     scr=["Acts 23:6-8"], diff="easy", tags=["mark", "sadducees", "resurrection"]),

dict(id="NT-O-0048", t=1131, b=1150, kind="fill_blank",
     q="By Jesus' time the Jews had accumulated hundreds of Laws, totalling ____________.",
     acc=["613", "six hundred and thirteen", "613 laws"],
     expl="Some religious leaders tried to distinguish between major and minor laws, and some taught that all were binding; Jesus' answer summarised them all in love for God and love for others.",
     exc="By Jesus' time, the Jews had accumulated hundreds of Laws, totaling 613.",
     scr=["Leviticus 19:18"], diff="medium", tags=["mark", "law", "greatest-commandment"]),

dict(id="NT-O-0049", t=1131, b=1155, kind="multiple_choice",
     q="Jesus told the law teacher that he was 'not far from the kingdom of God'. What, according to the syllabus, still separated him from it?",
     opts=[("His failure to become a follower of Jesus", True, ""),
           ("His ignorance of the two great commandments", False, "It was precisely his good answer about the two commandments that drew Jesus' words."),
           ("His manipulation of religious tradition", False, "The syllabus says he was not guilty of the manipulation for which Jesus condemned the scribes elsewhere."),
           ("His membership of the Sadducean party", False, "He was a teacher of the Law who had heard the discussion with the Sadducees, not one of them.")],
     expl="His answer showed him sincere and free of the scribes' manipulation of tradition; what he lacked was discipleship.",
     exc="That which separates him from the kingdom of God is his failure to become a follower of Jesus.",
     scr=[], diff="hard", tags=["mark", "kingdom-of-god", "discipleship"]),

dict(id="NT-O-0050", t=1131, b=1161, kind="multiple_choice",
     q="What does Jesus' question about David's son, quoting Psalm 110:1, strongly imply about the Messiah?",
     opts=[("That the Messiah is both God (David's Lord) and man (David's son) at the same time", True, ""),
           ("That the Messiah could not be descended from David at all", False, "Jesus does not deny the Davidic descent; He shows the Messiah is both son and Lord."),
           ("That David was mistaken in what he wrote", False, "The syllabus says David spoke by the Holy Spirit."),
           ("That the scribes were right to expect a purely political deliverer", False, "The point tells against, not for, a merely political expectation.")],
     expl="Jesus' rhetorical question pointed His listeners to one valid answer only: the Messiah is David's son and David's Lord at once, and He will restore the future Davidic kingdom on earth.",
     exc="the Messiah is David's son and David's Lord at the same time.",
     scr=["Psalms 110:1", "2 Samuel 7:16"], diff="hard", tags=["mark", "messiah", "davidic-sonship"]),

# ---------- 2.3 The Last Things (anchor 1170) ----------
dict(id="NT-O-0051", t=1170, b=1171, kind="multiple_choice",
     q="Which four disciples came to Jesus privately on the Mount of Olives to ask when the temple's destruction would occur?",
     opts=[("Peter, James, John and Andrew", True, ""),
           ("Peter, James, John and Philip", False, "Philip is not named among the four in this passage."),
           ("Peter, Andrew, Thomas and Judas", False, "Neither Thomas nor Judas appears in this scene."),
           ("James, John, Levi and Bartimaeus", False, "Bartimaeus was not one of the Twelve.")],
     expl="The four senior disciples asked both when the destruction would occur and what sign would indicate its imminence.",
     exc="the four senior disciples, Peter, James, John and Andrew got alone with Him and asked Him when the Temple's destruction would occur.",
     scr=["Luke 21:37"], diff="easy", tags=["mark", "olivet-discourse", "the-twelve"]),

dict(id="NT-O-0052", t=1170, b=1174, kind="multiple_response",
     q="Against what THREE kinds of deception or disturbance does the Olivet Discourse warn the disciples, as 'the beginning of the sufferings'?",
     opts=[("Imposters in the religious sphere", True, ""),
           ("Uprisings or disturbances in the political and international field", True, ""),
           ("Calamities in the physical realm", True, ""),
           ("Famine among the Christians of Judea", False, "The famine relieved by the Antioch collection belongs to the Acts narrative, not to this warning."),
           ("Divisions between Greek-speaking and Hebrew believers", False, "That dispute belongs to Acts 6, not to the Olivet Discourse.")],
     expl="Such things are incidental to the course of the age and are not necessarily to be taken as signs of the end; they are the beginning of birth pains.",
     exc="There would be imposters in the religious sphere, uprisings or disturbances in political and international field and calamities in the physical realm.",
     scr=[], diff="medium", tags=["mark", "olivet-discourse", "eschatology"]),

dict(id="NT-O-0053", t=1170, b=1195, kind="multiple_choice",
     q="What does the syllabus say about the time of Christ's personal return?",
     opts=[("The fact of His return is unalterably sure, but the time is locked in the counsels of the Father, so that even the Son does not share the secret", True, ""),
           ("The time was revealed to the four senior disciples on the Mount of Olives", False, "They were told signs, but not the time."),
           ("The time is to be calculated from the destruction of the temple", False, "No such calculation is offered in the syllabus."),
           ("Both the fact and the time remain uncertain", False, "The syllabus insists the fact of the return is unalterably sure.")],
     expl="In the voluntarily accepted limitations of His incarnation the Son does not share the secret of the time; the passage therefore teaches how to live while waiting.",
     exc="We are to learn that the fact of Christ's personal return is unalterably sure. The time",
     scr=["Acts 1:11", "Revelation 1:7"], diff="hard", tags=["mark", "second-coming", "watchfulness"]),

# ---------- 2.4 The Passion Narrative (anchor 1202) ----------
dict(id="NT-O-0054", t=1202, b=1204, kind="multiple_choice",
     q="Why did the Jewish leaders resolve not to arrest Jesus during the feast?",
     opts=[("Because it might provoke violent opposition from His supporters coming to Jerusalem from Galilee for the Passover", True, ""),
           ("Because arrests were forbidden by Roman law during festivals", False, "No Roman prohibition is mentioned in the syllabus."),
           ("Because they had not yet found any witnesses against Him", False, "The search for witnesses belongs to the trial itself."),
           ("Because Pilate had refused to hear the case during the feast", False, "Pilate does not enter the narrative until the trial.")],
     expl="Their desire was fulfilled through Judas Iscariot, who disclosed where Jesus might be found at night and almost alone.",
     exc="Their reason was that it might provoke violent opposition on the part of supporters of Jesus who would be coming to Jerusalem from Galilee to observe the Passover.",
     scr=[], diff="medium", tags=["mark", "passion", "plot"]),

dict(id="NT-O-0055", t=1202, b=1226, kind="multiple_choice",
     q="What was the prearranged signal by which the two disciples were to find the room for the Passover?",
     opts=[("A man carrying a jar of water, since normally only women carried water jars", True, ""),
           ("A lamp burning in an upper window", False, "No such signal is mentioned in the syllabus."),
           ("A servant bearing a wineskin, since only men carried wineskins", False, "The syllabus says men carried wineskins; the eye-catching sight was a man with a water jar."),
           ("A palm branch laid across the doorway", False, "Palm branches belong to the entry into Jerusalem.")],
     expl="For security reasons the participants were not disclosed and the location kept secret, so the unusual sight of a man carrying a water jar served as a signal.",
     exc="A man carrying a jar of water would meet the two disciples. Normally only women carried water jars (men carried wineskins). This unusual eye-catching sight suggests that it was a prearranged signal.",
     scr=["Luke 22:8"], diff="medium", tags=["mark", "last-supper", "passover"]),

dict(id="NT-O-0056", t=1202, b=1234, kind="multiple_choice",
     q="From which Psalms was the hymn most likely taken which Jesus and the disciples sang before going out to the Mount of Olives?",
     opts=[("Psalms 115-118, the Hallel", True, ""),
           ("Psalms 22-24, the Psalms of the Passion", False, "Psalm 22 is quoted from the cross, but it is not the hymn of the Last Supper."),
           ("Psalms 120-134, the Songs of Ascents", False, "The syllabus names the Hallel, Psalms 115-118."),
           ("Psalm 110 alone", False, "Psalm 110 is quoted in the debate about David's son.")],
     expl="The Hallel was traditionally sung to conclude the Passover; after it, Jesus led the disciples out and quoted Zechariah 13:7 concerning the scattering of the flock.",
     exc="The hymn they sang was most likely taken from Psalms 115-118, the Hallel, which were traditionally sung to conclude the Passover.",
     scr=["Zechariah 13:7"], diff="medium", tags=["mark", "last-supper", "hallel"]),

dict(id="NT-O-0057", t=1202, b=1260, kind="multiple_choice",
     q="How had the false witnesses at the trial twisted Jesus' actual words about the temple?",
     opts=[("He had said 'Destroy this temple and in three days I will raise it up', not 'I will destroy this temple'", True, ""),
           ("He had said the temple would stand for ever, not that it would fall", False, "Jesus had predicted the temple's complete destruction in chapter 13."),
           ("He had spoken of Herod's temple, but they applied it to the tabernacle", False, "The reverse is true: He was speaking of His own body, not of Herod's temple."),
           ("He had never spoken of the temple at all", False, "He had spoken of it, but not in the form the witnesses alleged.")],
     expl="Jesus was speaking not about Herod's Temple but about His own death and resurrection.",
     exc="He did not say \"I will destroy this Temple,\" He said \"Destroy this temple and in three days I will raise it up\" (Jn. 2:19).",
     scr=["John 2:19"], diff="hard", tags=["mark", "trial", "temple"]),

dict(id="NT-O-0058", t=1202, b=1245, kind="multiple_choice",
     q="How does the syllabus explain the 'cup' from which Jesus shrank in Gethsemane?",
     opts=[("It was the alienation Jesus knew would occur when separated from God the Father at the cross", True, ""),
           ("It was the physical pain of scourging and crucifixion alone", False, "The syllabus says it was certainly more than physical suffering, since many a martyr has shown greater courage."),
           ("It was the fear of desertion by His disciples", False, "That desertion is predicted, but it is not the cup."),
           ("It was the cup of the Passover which Judas had defiled", False, "No such interpretation is offered.")],
     expl="It was the agony of His sinless soul being made sin and exposed to the divine judgment of sin; the sinless Son of God took on our sins and was in that moment separated from the Father.",
     exc="this \"cup\" was the alienation Jesus knew would occur when separated from God the Father, at the cross (Heb. 5:7-9).",
     scr=["2 Corinthians 5:21", "Hebrews 5:7-9"], diff="hard", tags=["mark", "gethsemane", "atonement"]),

dict(id="NT-O-0059", t=1202, b=1269, kind="true_false",
     q="The syllabus contrasts Peter and Judas by saying that Peter's remorse opened the way for repentance and a reaffirmation of his loyalty, whereas Judas had no faith in Jesus that could be renewed.",
     ans=True,
     expl="Peter's third denial was punctuated by the cock's second crowing, and he broke down weeping bitterly; but his remorse led to restoration.",
     exc="Peter had faith in Jesus that could be renewed, but Judas did not.",
     scr=["Luke 22:61"], diff="medium", tags=["mark", "peter", "judas", "denial"]),

# ---------- Chapter 15 (anchor 1271) ----------
dict(id="NT-O-0060", t=1271, b=1279, kind="multiple_choice",
     q="The three non-religious charges laid against Jesus before Pilate are summarised in the syllabus as which offences?",
     opts=[("Tax evasion, treason and terrorism", True, ""),
           ("Blasphemy, sorcery and sedition", False, "Blasphemy was the religious charge which would mean nothing to Pilate."),
           ("Theft, murder and rebellion", False, "Those were the crimes of Barabbas, not the charges against Jesus."),
           ("Sabbath-breaking, defilement and false prophecy", False, "These were earlier religious accusations, not the charges before Pilate.")],
     expl="Because blasphemy was a religious crime that would mean nothing to a Roman governor, the Jews accused Jesus of encouraging non-payment of taxes, of claiming to be a king, and of causing riots.",
     exc="Tax evasion, treason, and terrorism - all of these would be cause for Pilate's concern.",
     scr=[], diff="medium", tags=["mark", "trial", "pilate"]),

dict(id="NT-O-0061", t=1271, b=1273, kind="multiple_choice",
     q="Why did Jesus have to be sentenced by a Roman leader, and why did the Jewish leaders want death by crucifixion in particular?",
     opts=[("The Romans had taken away the Jews' right to inflict capital punishment; and the leaders believed crucifixion brought a curse from God, hoping to persuade the people that Jesus was cursed", True, ""),
           ("Jewish law forbade executions during Passover; and crucifixion was the swiftest death", False, "Speed is not the reason given, and the syllabus grounds the choice in the idea of a curse."),
           ("Pilate had demanded jurisdiction over all religious cases; and crucifixion was a Jewish penalty", False, "Crucifixion was a Roman penalty and the reason given is different."),
           ("The Sanhedrin lacked a quorum; and crucifixion avoided ritual defilement", False, "Neither point appears in the syllabus.")],
     expl="The Jewish leaders wanted Jesus executed on a cross because they believed such a death brought a curse from God, so that the people would think Him cursed rather than blessed.",
     exc="More important, the Jewish leaders wanted Jesus executed on a cross, a method of crucifixion they believed brought a curse from God, (cf. Dt. 21:23).",
     scr=["Deuteronomy 21:23"], diff="hard", tags=["mark", "crucifixion", "pilate"]),

dict(id="NT-O-0062", t=1271, b=1302, kind="multiple_choice",
     q="For what period did total darkness engulf the whole land at the crucifixion?",
     opts=[("From the sixth hour (noon) until the ninth hour (3 pm)", True, ""),
           ("From the third hour (9 am) until the sixth hour (noon)", False, "Jesus hung on the cross in daylight for those three hours; the darkness came afterwards."),
           ("From sunset on Friday until sunset on Saturday", False, "That is the reckoning of the Sabbath, not of the darkness."),
           ("For the whole day from dawn to dusk", False, "The syllabus specifies a three-hour period.")],
     expl="The darkness was probably a cosmic sign of God's judgment on human sin, which was placed on Jesus, and it visualised what His cry from Psalm 22:1 expressed.",
     exc="Jesus hanged on the cross for three hours in the daylight (9am till noon) and then at the sixth hour (noon) total darkness engulfed the whole land (Palestine and environs) until the ninth hour (3 pm).",
     scr=["Psalms 22:1", "Amos 8:9-10"], diff="medium", tags=["mark", "crucifixion", "darkness"]),

dict(id="NT-O-0063", t=1271, b=1299, kind="multiple_response",
     q="Mark records five supernatural events accompanying Jesus' death. Which THREE of the following are among those the syllabus lists first?",
     opts=[("Darkness over the land", True, ""),
           ("Jesus' cry 'My God, my God...'", True, ""),
           ("Jesus' loud cry before He breathed His last", True, ""),
           ("An earthquake which opened the tombs", False, "No earthquake is listed among the five events in the syllabus's account of Mark."),
           ("The rolling away of the stone by an angel", False, "That belongs to the resurrection narrative, not to the death of Jesus.")],
     expl="The syllabus lists five accompanying events: darkness, the cry of dereliction, the loud cry, the tearing of the temple curtain, and the centurion's confession.",
     exc="In this portion of the narrative Mark recorded five supernatural events that accompanied",
     scr=[], diff="medium", tags=["mark", "crucifixion", "signs"]),

dict(id="NT-O-0064", t=1271, b=1306, kind="multiple_choice",
     q="What did the tearing of the veil before the Holy of Holies signify?",
     opts=[("That Jesus' death for our sins had opened the way for us to approach our Holy God", True, ""),
           ("That the temple would soon be destroyed by the Romans", False, "The destruction of the temple is predicted separately, in the Olivet Discourse."),
           ("That the office of high priest had passed to the apostles", False, "No such transfer is taught here."),
           ("That the Day of Atonement had been abolished for the Jews only", False, "The syllabus draws a wider conclusion about access to God.")],
     expl="The veil symbolically separated the Holy God from sinful mankind, and the place was entered only once a year by the High Priest on the Day of Atonement.",
     exc="When Jesus died, the veil was split in two, showing that Jesus' death for our sins had opened the way for us to approach our Holy God.",
     scr=[], diff="medium", tags=["mark", "crucifixion", "atonement", "temple"]),

dict(id="NT-O-0065", t=1271, b=1309, kind="multiple_choice",
     q="Why was it important, according to the syllabus, that Joseph of Arimathea came to bury Jesus before the Sabbath began?",
     opts=[("Had the Roman soldiers taken the body down, no Jew could have confirmed His death and the resurrection could have been disputed", True, ""),
           ("Because Jewish law required burial by a member of the family", False, "Joseph was a member of the Sanhedrin, not of the family."),
           ("Because the tomb had to be purchased before sundown", False, "The tomb was Joseph's own unused tomb."),
           ("Because the Romans charged a fee for bodies left overnight", False, "No such fee is mentioned in the syllabus.")],
     expl="It was against Jewish law to work or travel on the Sabbath, and against Jewish law to leave a dead body exposed overnight; Joseph therefore acted before sundown on Friday.",
     exc="And had the Roman soldiers taken Jesus' body, no Jew could have confirmed His death, and they could have disputed His resurrection.",
     scr=["Deuteronomy 21:23"], diff="hard", tags=["mark", "burial", "resurrection"]),

# ---------- 3.1 The Women's Visit (anchor 1320) ----------
dict(id="NT-O-0066", t=1320, b=1321, kind="true_false",
     q="The young man robed in white whom the women found sitting in the tomb was, according to the syllabus, clearly an angel.",
     ans=True,
     expl="The women, ignorant that the tomb had been sealed and guarded, were astonished to find him there; he told them that Jesus had risen and that they should notify the disciples and Peter.",
     exc="The young man was clearly an angel.",
     scr=[], diff="easy", tags=["mark", "resurrection", "angel"]),

# ---------- 3.2 Disputed Conclusion (anchor 1325) ----------
dict(id="NT-O-0067", t=1325, b=1326, kind="multiple_choice",
     q="On what evidence do nearly all scholars conclude that Mark 16:9-20 is not part of the original text of the Gospel?",
     opts=[("Its dissimilarity in vocabulary and style, and its absence from the oldest and best manuscripts, Sinaiticus and Vaticanus", True, ""),
           ("Its disagreement with the resurrection accounts in the other Gospels", False, "Disagreement with the other Gospels is not the ground given."),
           ("A statement to that effect by the Fathers Papias and Irenaeus", False, "Papias and Irenaeus are cited concerning Mark's relation to Peter, not concerning this passage."),
           ("Its absence from every Latin and Syriac version", False, "The syllabus names Sinaiticus and Vaticanus specifically.")],
     expl="The syllabus adds that it is nevertheless not to be deduced that these verses are not part of the inspired Word of God.",
     exc="The evidence for this inference being their considerable dissimilarity from the rest of this Gospel both with regards to vocabulary and style, and especially their absence from the oldest and best manuscripts of the Gospel, namely Sinaiticus and Vaticanus.",
     scr=[], diff="hard", tags=["mark", "textual-criticism", "manuscripts"]),

dict(id="NT-O-0068", t=1325, b=1335, kind="true_false",
     q="Mark 16:16 teaches that baptism is a necessary requirement for salvation.",
     ans=False,
     expl="The syllabus notes that the second half of the verse shows by contrast that it is unbelief that condemns; baptism alone without faith does not save.",
     exc="V. 16 does not mean that baptism is a necessary requirement for salvation.",
     scr=[], diff="medium", tags=["mark", "baptism", "salvation"]),

]
