# -*- coding: utf-8 -*-
# Objective questions for UNITS THREE, FOUR and FIVE

REST = [

# =========================== GALATIANS ===========================
dict(id="G1", t=2084, b=2088, kind="multiple_choice",
     q="What was the one basic problem disturbing the churches in Galatia?",
     opts=[("The teaching of Judaizers", True, ""),
           ("Persecution by the Roman authorities", False, "The syllabus names an internal doctrinal threat, not state persecution."),
           ("Division between rich and poor at the love feast", False, "That problem belongs to Corinth, not to Galatia."),
           ("Denial of the resurrection of the dead", False, "That error is dealt with in 2 Timothy, where Hymenaeus and Philetus are named.")],
     expl="The Judaizers' teaching threatened the churches on two fronts: Paul's gospel of justification by faith, and Paul's personal authority as an apostle.",
     exc="There was one basic problem disturbing the churches in Galatia, the teaching of Judaizers.",
     scr=[], diff="easy", tags=["galatians", "judaizers", "introduction"]),

dict(id="G2", t=2084, b=2096, kind="multiple_choice",
     q="What was the strategy of the Judaizers for destroying Paul's influence?",
     opts=[("That because he was not one of the Twelve his authority was not apostolic, and whatever he knew he got second-hand and garbled at that", True, ""),
           ("That he had never seen the risen Lord and had invented his conversion", False, "The syllabus states their argument in terms of apostolic standing and second-hand knowledge."),
           ("That he was a Gentile and therefore ignorant of the Law", False, "Paul's Jewish credentials were never in doubt; his apostolic standing was the point of attack."),
           ("That he took money from the churches he founded", False, "No such accusation appears in the syllabus.")],
     expl="Because Paul was the chief obstacle to the Judaizers' success, they attacked him at his 'Achilles heel' so as to silence him.",
     exc="because he was not one of the Twelve Apostles, his authority was not apostolic; that whatever he knew he got second-hand and got it garbled at that.",
     scr=[], diff="hard", tags=["galatians", "apostleship", "judaizers"]),

dict(id="G3", t=2112, b=2116, kind="multiple_choice",
     q="Where does the syllabus say Paul received his gospel directly from the Lord Jesus Christ Himself?",
     opts=[("In Arabia", True, ""),
           ("In Damascus, from Ananias", False, "Ananias healed and baptised Saul; the gospel itself came by revelation."),
           ("In Jerusalem, from the Twelve", False, "Paul insists precisely that he neither received it by human tradition nor was taught it."),
           ("In Antioch, from Barnabas", False, "Barnabas brought Paul to the work at Antioch, but did not teach him the gospel.")],
     expl="Paul emphasises that the gospel he preached was no human gospel: he neither received it by human tradition nor was taught it, but it came through an unveiling of Jesus Christ.",
     exc="Here, he proves that he received his gospel direct from our Lord Jesus Christ himself, in Arabia.",
     scr=[], diff="medium", tags=["galatians", "apostolic-authority", "revelation"]),

dict(id="G4", t=2132, b=2146, kind="multiple_choice",
     q="How does the syllabus explain the believer's freedom from the Law in Galatians 2:20-21?",
     opts=[("The Law demanded death for those who broke it, but Christ paid that death penalty; so the Law killed Him and those joined to Him by faith, freeing them to live for God", True, ""),
           ("The Law was abolished at the Jerusalem Council, so it no longer applies", False, "The Council settled the question of Gentile circumcision; the argument here is about union with Christ."),
           ("The Law was never binding on Jews who had faith", False, "Paul argues that, as Jews, he and Peter had experienced the inability of the Law to save."),
           ("The believer keeps the Law by his own strength once he is justified", False, "The syllabus teaches the opposite: what the Law could not do, grace had done.")],
     expl="Paul describes the transformation of a person who has come to God by faith in Christ in terms of a death and a resurrection; having been united to Christ, believers share in His death, burial and resurrection.",
     exc="The Law demanded death for those who broke it, but Christ paid that death penalty for all sinners. In this way the Law killed him and those joined to him by faith, freeing them to live for God",
     scr=["Romans 7:4"], diff="hard", tags=["galatians", "justification", "union-with-christ"]),

dict(id="G5", t=2149, b=2150, kind="true_false",
     q="Paul's answer to the Judaizers' claim that obedience to the Law would complete salvation was that to supplement the work of Christ is to supplant it.",
     ans=True,
     expl="There can be only one way of salvation, and that is by faith in Christ alone; to embrace a doctrine which declared the death of Christ unnecessary was irrational.",
     exc="But Paul argued that to supplement the work of Christ is to supplant it.",
     scr=[], diff="medium", tags=["galatians", "faith", "law"]),

dict(id="G6", t=2175, b=2183, kind="multiple_choice",
     q="Which saying does the syllabus quote from C. H. Mackintosh to contrast law and gospel?",
     opts=[("'The Law demands strength from one who has none and curses him if he cannot display it. The Gospel gives strength to one who has none and blesses him in the exhibition of it.'", True, ""),
           ("'The Law is the believer's rule of life, and the Gospel his comfort in failure.'", False, "The syllabus lists this kind of teaching among the errors legalism still produces."),
           ("'Grace to you and peace from God our Father and the Lord Jesus Christ.'", False, "That is Paul's own greeting quoted in the conclusion of the epistle."),
           ("'The Law commands but does not enable; the Gospel enables but does not command.'", False, "The syllabus says grace provides what the law demands and then enables man to live consistently, but this is not the quoted saying.")],
     expl="The point of the chapter is that the law commands but does not enable, while grace provides what the law demands and then enables a man to live by the power of the Holy Spirit.",
     exc="C. H. Mackintosh has said \"The Law demands strength from one who has none and curses him if he cannot display it. The Gospel gives strength to one who has none and blesses him in the exhibition of it.\"",
     scr=["James 2:10"], diff="medium", tags=["galatians", "law-and-grace", "quotations"]),

dict(id="G7", t=2188, b=2190, kind="fill_blank",
     q="All the virtues listed in Galatians 5:22-23 constitute ____________ fruit, so that all of them must be manifested in the Christian who walks by the Spirit.",
     acc=["one", "one (singular)", "a single", "one singular"],
     expl="The Christian who walks by the Spirit does not manifest the desires of the flesh but bears the fruit of the Spirit, and so fulfils the just requirement of the law summed up in loving one's neighbour as oneself.",
     exc="all the virtues listed in verses 22 and 23 constitute one fruit (singular)",
     scr=[], diff="medium", tags=["galatians", "fruit-of-the-spirit", "holy-spirit"]),

# =========================== 1 TIMOTHY ===========================
dict(id="P1", t=2229, b=2239, kind="multiple_choice",
     q="Which letters are known as the Pastoral Epistles, and what is distinctive about them?",
     opts=[("The two letters to Timothy and the one to Titus; they were addressed to individuals and not to congregations", True, ""),
           ("The letters to Timothy, Titus and Philemon; they were written from prison", False, "Philemon is not counted among the Pastorals in the syllabus."),
           ("The letters to Timothy alone; they were written to a congregation at Ephesus", False, "Titus belongs with them, and they were addressed to individuals."),
           ("The letters to Timothy and Titus; they were written before Paul's first imprisonment", False, "The distinguishing mark given is that they were addressed to individuals, not congregations.")],
     expl="Paul was advanced in age, about seventy, when he wrote them, so that they contain his farewell address to ministers and Christian workers, showing the mellow wisdom of old age.",
     exc="The two letters to Timothy and the one to Titus are known as Pastoral Epistles. They were addressed to individuals and not to congregations.",
     scr=[], diff="easy", tags=["1-timothy", "pastoral-epistles", "introduction"]),

dict(id="P2", t=2262, b=2274, kind="fill_blank",
     q="Instead of stressing external beauty according to the world's standards, Christian women should adorn themselves with (literally 'by means of') ____________.",
     acc=["good deeds", "good works", "good deeds."],
     expl="This was no plea for women to make themselves unattractive; it was an exhortation to reject the world's yardstick for measuring beauty and to adopt heaven's standard.",
     exc="They should adorn themselves with (lit. \"by means of') good deeds.",
     scr=["1 Samuel 16:7"], diff="medium", tags=["1-timothy", "women", "public-worship"]),

dict(id="P3", t=2279, b=2286, kind="multiple_choice",
     q="What does the word 'Deacon' mean, and to what does it refer in 1 Timothy 3?",
     opts=[("'Servant, helper'; it refers to the bishops' assistant", True, ""),
           ("'Elder'; it refers to the ruling council of the congregation", False, "Elders are treated separately in chapter 5; deacon means servant or helper."),
           ("'Overseer'; it refers to the pastoral supervisor", False, "That is the sense of bishop, not of deacon."),
           ("'Steward'; it refers to the keeper of the church treasury", False, "The syllabus defines the word as servant or helper, the bishops' assistant.")],
     expl="Deacons take care of the mundane matters of church life, particularly the distribution of charity, and must be proved blameless through examination before entering office.",
     exc="\"Deacon\" means \"servant, helper\" and refers to the bishops' assistant.",
     scr=[], diff="easy", tags=["1-timothy", "deacons", "ministry"]),

dict(id="P4", t=2293, b=2295, kind="true_false",
     q="The false teaching against which Paul warns in 1 Timothy 4 comprised two prohibitions: marriage and the eating of certain foods.",
     ans=True,
     expl="Paul opposed these prohibitions because they conflict with the divine ordinance, resting his argument on the fundamental principle that what a good Creator creates must be good.",
     exc="The false teaching comprised two prohibitions: marriage and eating of certain foods.",
     scr=["Genesis 1:31"], diff="medium", tags=["1-timothy", "false-teaching", "creation"]),

dict(id="P5", t=2297, b=2323, kind="multiple_choice",
     q="In Timothy's public ministry, what does 'exhortation' (preaching) include, according to the syllabus?",
     opts=[("Exposition and application of the passages read, addressed to Christians", True, ""),
           ("Evangelism addressed to non-Christians", False, "The syllabus distinguishes preaching to non-Christians as evangelism rather than exhortation."),
           ("A catechetical treatment of the truths of the faith", False, "That is the description given of teaching, the third essential."),
           ("The public reading of the word of God aloud in the congregation", False, "That is the first of the three essentials, distinct from exhortation.")],
     expl="The three ministerial essentials of Timothy's public service are the public reading of Scripture, preaching, which is exhortation, and teaching.",
     exc="The term includes exposition and application of the passages read. It suggests preaching to Christians.",
     scr=["Nehemiah 8:7-8", "Colossians 4:16"], diff="hard", tags=["1-timothy", "preaching", "ministry"]),

dict(id="P6", t=2352, b=2375, kind="multiple_response",
     q="Timothy, as a man of God, was to chase after personal virtues of eternal value. Which THREE of the following does the syllabus list among them?",
     opts=[("Righteousness", True, ""),
           ("Godliness", True, ""),
           ("Steadfastness", True, ""),
           ("Riches", False, "Riches belong to the 'some people' of verse 10 from whom Timothy is contrasted."),
           ("Circumcision", False, "Circumcision is the issue of Galatians, not of Paul's charge to Timothy here.")],
     expl="The elements of eternal value are given as righteousness, godliness, faith, love, steadfastness and gentleness; Timothy was not only to flee ungodliness but also to fight the good fight of the faith.",
     exc="Here the elements of eternal value (Christian character) are given as righteousness, godliness, faith, love, steadfastness, gentleness.",
     scr=[], diff="medium", tags=["1-timothy", "christian-character", "charge-to-timothy"]),

dict(id="P7", t=2352, b=2398, kind="true_false",
     q="In the closing benediction of 1 Timothy, 'Grace be with you', the word 'you' is plural, indicating Paul's awareness that the letter would be read widely in the churches.",
     ans=True,
     expl="The letter was addressed to Timothy personally, but it was surely to be read to the church for its own edification as well as to the young minister.",
     exc="\"You\" is in the plural, (an indication of his awareness that this letter would be read widely in the churches",
     scr=["Colossians 4:18", "Titus 3:15"], diff="medium", tags=["1-timothy", "benediction", "letters"]),

# =========================== 2 TIMOTHY ===========================
dict(id="Q1", t=2428, b=2431, kind="multiple_choice",
     q="What is the primary theme of 2 Timothy?",
     opts=[("The need for faithfulness in the face of hardship", True, ""),
           ("Justification by faith apart from the works of the Law", False, "That is the theme of Galatians."),
           ("How people ought to conduct themselves in God's household", False, "That is the stated purpose of 1 Timothy."),
           ("The unity of Jew and Gentile in one church", False, "That question belongs to Acts and Galatians.")],
     expl="The purpose of the letter was to encourage Timothy in his ministry at Ephesus; Paul wrote it in prison, and it was his last letter to Timothy.",
     exc="The primary theme of the letter is the need for faithfulness in the face of hardship.",
     scr=[], diff="easy", tags=["2-timothy", "introduction", "theme"]),

dict(id="Q2", t=2445, b=2456, kind="multiple_choice",
     q="According to 2 Timothy 1:7, God did not give us a spirit of timidity. Which three virtues, supplied by the Holy Spirit, should characterise Timothy instead?",
     opts=[("Power, love and self-discipline", True, ""),
           ("Faith, hope and love", False, "That triad belongs to 1 Corinthians, not to this verse."),
           ("Righteousness, godliness and gentleness", False, "Those come in the charge of 1 Timothy 6:11, not here."),
           ("Wisdom, knowledge and discernment", False, "These are not the virtues named in 2 Timothy 1:7.")],
     expl="Timothy may have been intimidated by the opposition to Paul and to the gospel, and ashamed at having to defend a prisoner; but Paul holds that such timidity has no place in God's service.",
     exc="Instead God gives a spirit of power (1 Cor. 2:4) oflove (cf. 1 Tim. 1:5) and of self-discipline (cf. 1 Tim. 4:7).",
     scr=["2 Timothy 1:8", "1 Corinthians 1:18-25"], diff="medium", tags=["2-timothy", "holy-spirit", "courage"]),

dict(id="Q3", t=2473, b=2479, kind="fill_blank",
     q="The principle by which what Timothy had heard from Paul was to be entrusted to reliable men who would be qualified to teach others has come to be called ____________.",
     acc=["the ministry of multiplication", "ministry of multiplication", "\"the ministry of multiplication\""],
     expl="Paul, nearing the end of his own ministry, charged Timothy to pass on the same truth he had received to men who would in turn teach others.",
     exc="This principle has come to be called \"the ministry of multiplication\".",
     scr=["1 Timothy 3:2", "Titus 1:9"], diff="medium", tags=["2-timothy", "discipleship", "training"]),

dict(id="Q4", t=2487, b=2499, kind="multiple_response",
     q="By having nothing to do with the false teachers, Timothy would be a vessel with which THREE of the following qualities?",
     opts=[("For noble use", True, ""),
           ("Made holy", True, ""),
           ("Useful to the master", True, ""),
           ("Made of wood and clay", False, "In the metaphor the wood and clay vessels stand for those put to ignoble use."),
           ("Set apart for the distribution of charity", False, "That is the work of deacons in 1 Timothy, not part of this metaphor.")],
     expl="In a large household are containers of gold and silver and others of wood and clay, some for noble purposes and some for ignoble; the metaphor shows how one may become an instrument for noble purposes by cleansing himself.",
     exc="In this way he would be a vessel (1) for noble use; (2) made holy; (3) useful to the master; (4) prepared for any good work",
     scr=["2 Timothy 3:16"], diff="medium", tags=["2-timothy", "holiness", "metaphor"]),

dict(id="Q5", t=2514, b=2517, kind="true_false",
     q="Although Paul catalogued the marks of moral decadence under a prediction about 'the last days', he considered them to be already present in Ephesus, though they would intensify with time.",
     ans=True,
     expl="Timothy therefore had to beware of such people and have nothing to do with them.",
     exc="it is clear that Paul considered them to be already present in Ephesus, though they would intensify with time.",
     scr=[], diff="medium", tags=["2-timothy", "last-days", "moral-decay"]),

dict(id="Q6", t=2519, b=2528, kind="multiple_choice",
     q="What does Paul mean in 2 Timothy 3:16 by saying that all Scripture is God-breathed?",
     opts=[("That God's words were given through men superintended by the Holy Spirit, so that their writings are without error", True, ""),
           ("That the Scriptures become the word of God when they are read aloud in the congregation", False, "The public reading of Scripture is a separate instruction in 1 Timothy 4:13."),
           ("That only the Old Testament is inspired", False, "The syllabus notes that the Scriptures at that time consisted of the Old Testament, but the point made concerns inspiration, not limitation."),
           ("That the Scriptures were dictated to the prophets by angels", False, "No such account of inspiration is given.")],
     expl="This fact was virtually taken for granted by the Jews, and led Paul to declare the usefulness of the word for teaching, rebuking, correcting and training in righteousness.",
     exc="God's words were given through men superintended by the Holy Spirit so that their writings are without error.",
     scr=["1 Timothy 5:20", "2 Timothy 4:2"], diff="medium", tags=["2-timothy", "inspiration", "scripture"]),

dict(id="Q7", t=2533, b=2535, kind="fill_blank",
     q="Paul's need for Timothy was intensified by the defection of Demas, who, instead of loving the Lord's appearing, loved this world and deserted the apostle for ____________.",
     acc=["Thessalonica", "Thessalonica.", "the comfort of Thessalonica"],
     expl="No blame is suggested concerning the absence of Crescens and Titus; it seems they had been dispatched to the Lord's work elsewhere, Crescens to Galatia and Titus to Dalmatia.",
     exc="Demas deserted the apostle to embrace the deceptive, freedom or comfort of Thessalonica.",
     scr=[], diff="medium", tags=["2-timothy", "demas", "companions"]),

]
